Repository elastic/apm-agent-nodejs, pull requests merged in 2018-12, with the labels that each got.

#700 fix(hapi): ignore internal events channel
  lib/instrumentation/modules/hapi.js
  test/instrumentation/modules/hapi.js
Labels: [zube]: In Review, bug

#632 test(ci): add Node.js 11 to CI test matrix
  .travis.yml
  test/.jenkins_nodejs.yml
  test/.jenkins_tav_nodejs.yml
Labels: [zube]: In Progress, ci

#704 docs: fix cross document links (1.x)
  docs/agent-api.asciidoc
  docs/compatibility.asciidoc
  docs/index.asciidoc
  docs/intro.asciidoc
Labels: docs

#703 docs: fix cross document links (master)
  docs/agent-api.asciidoc
  docs/index.asciidoc
  docs/intro.asciidoc
  docs/supported-technologies.asciidoc
Labels: docs

#702 fix: use randomFillSync polyfill on Node.js <6.13.0
  lib/instrumentation/trace-context.js
  package.json
Labels: [zube]: In Review

#708 docs: version fix
  docs/index.asciidoc
Labels: docs

#707 docs: version fix
  docs/index.asciidoc
Labels: docs

#711 fix: don't throw on older versions of Node.js 6
  lib/instrumentation/http-shared.js
Labels: [zube]: In Review

#715 test(tav): clean up .tav.yml file
  .tav.yml
Labels: [zube]: In Review

#719 test(ws): fix tests for ws on older Node versions
  .tav.yml
Labels: [zube]: In Review

#723 docs: fix wrong link in README.md ToC
  README.md
Labels: [zube]: In Review, docs

#724 docs: link to 1.x docs from 1.x README.md ToC
  README.md
Labels: [zube]: In Review, docs

#726 chore(package): bump random-poly-fill to ^1.0.1
  package.json
Labels: [zube]: In Review

#727 chore: update engines field in package.json
  package.json
Labels: [zube]: In Review

#728 chore: update package.json keywords
  package.json
Labels: [zube]: In Review

#722 chore: add .backportrc.json
  .backportrc.json
  .npmignore
Labels: [zube]: In Review

#733 test(knex): add knex@^0.16.0 to TAV test matrix
  .tav.yml
  package.json
Labels: [zube]: In Review

#736 docs: remove experimental support text
  docs/supported-technologies.asciidoc
Labels: docs

#735 Closes #732
  lib/agent.js
Labels: [zube]: In Review

#743 test(ci): fix apollo-server-express tests on older Node versions
  test/instrumentation/modules/apollo-server-express.js
Labels: ci

#751 docs: update code samples
  docs/agent-api.asciidoc
  docs/express.asciidoc
  docs/hapi.asciidoc
  docs/koa.asciidoc
  docs/lambda.asciidoc
  docs/restify.asciidoc
Labels: docs

#747 Fix graphql error handling (#1)
  lib/instrumentation/modules/graphql.js
  test/instrumentation/modules/graphql.js
Labels: [zube]: In Review, bug

#756 fix(graphql): fix span name for unknown queries
  lib/instrumentation/modules/graphql.js
  test/instrumentation/modules/graphql.js
Labels: [zube]: In Review

#754 test(tav): don't test release candidates
  .tav.yml
Labels: [zube]: In Review

#757 feat(span): add tags to spans
  docs/agent-api.asciidoc
  docs/span-api.asciidoc
  docs/transaction-api.asciidoc
  lib/agent.js
  lib/instrumentation/generic-span.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  test/agent.js
  test/config.js
  test/instrumentation/index.js
  test/instrumentation/modules/http/basic.js
  test/instrumentation/modules/http/outgoing.js
  test/instrumentation/span.js
  test/instrumentation/transaction.js
  test/integration/api-schema/basic.js
Labels: [zube]: In Review

#759 test: simplify transaction tests
  test/instrumentation/_instrumentation.js
  test/instrumentation/span.js
  test/instrumentation/transaction.js
Labels: [zube]: In Review

#762 refactor: improve span payload encoding
  lib/instrumentation/span.js
Labels: [zube]: In Review
