Repository elastic/apm-agent-nodejs, pull requests merged in 2018-11, with the labels that each got.

#652 test(mysql2): pin mysql2 to v1.6.1
  .tav.yml
  package.json
Labels: [zube]: In Review

#656 test(mysql2): un-pin mysql2 dev dependency
  .tav.yml
  package.json
  test/config.js
  test/instrumentation/modules/mysql2/mysql.js
  test/instrumentation/modules/mysql2/pool-release-1.js
Labels: [zube]: In Review

#658 test(hapi): fix hapi tav tests for node 4
  test/instrumentation/modules/hapi.js
Labels: [zube]: In Review

#644 feat(config): custom transport
  lib/agent.js
  lib/config.js
  lib/instrumentation/index.js
  test/config.js
  test/instrumentation/_agent.js
  test/instrumentation/github-issue-75.js
  test/instrumentation/index.js
  test/instrumentation/modules/apollo-server-express.js
  test/instrumentation/modules/cassandra/cassandra.js
  test/instrumentation/modules/elasticsearch.js
  test/instrumentation/modules/express-graphql.js
  test/instrumentation/modules/express-queue.js
  test/instrumentation/modules/express.js
  test/instrumentation/modules/finalhandler.js
  test/instrumentation/modules/graphql.js
  test/instrumentation/modules/handlebars.js
  test/instrumentation/modules/hapi.js
  test/instrumentation/modules/http/aborted-requests-disabled.js
  test/instrumentation/modules/http/aborted-requests-enabled.js
  test/instrumentation/modules/http/basic.js
  test/instrumentation/modules/http/bind-write-head-to-transaction.js
  test/instrumentation/modules/http/blacklisting.js
  test/instrumentation/modules/http/outgoing.js
  test/instrumentation/modules/http/request.js
  test/instrumentation/modules/http/sse.js
  test/instrumentation/modules/http2.js
  test/instrumentation/modules/ioredis.js
  test/instrumentation/modules/koa-router/index.js
  test/instrumentation/modules/mongodb-core.js
  test/instrumentation/modules/mysql/mysql.js
  test/instrumentation/modules/mysql2/mysql.js
  test/instrumentation/modules/pg/knex.js
  test/instrumentation/modules/pg/pg.js
  test/instrumentation/modules/redis.js
  test/instrumentation/modules/restify.js
  test/instrumentation/modules/tedious.js
  test/instrumentation/modules/ws.js
  test/sourcemaps/index.js
Labels: [zube]: In Review, enhancement

#663 fix: promise.then() resolve point
  lib/instrumentation/es6-wrapped-promise.js
  lib/instrumentation/patch-async.js
  test/instrumentation/async-hooks.js
Labels: [zube]: In Review, bug

#642 feat: simplified spans
  docs/agent-api.asciidoc
  docs/span-api.asciidoc
  docs/transaction-api.asciidoc
  docs/upgrade-to-v1.asciidoc
  docs/upgrade-to-v2.asciidoc
  lib/agent.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/cassandra-driver.js
  lib/instrumentation/modules/elasticsearch.js
  lib/instrumentation/modules/graphql.js
  lib/instrumentation/modules/handlebars.js
  lib/instrumentation/modules/http2.js
  lib/instrumentation/modules/ioredis.js
  lib/instrumentation/modules/mongodb-core.js
  lib/instrumentation/modules/mysql.js
  lib/instrumentation/modules/mysql2.js
  lib/instrumentation/modules/pg.js
  lib/instrumentation/modules/redis.js
  lib/instrumentation/modules/tedious.js
  lib/instrumentation/modules/ws.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  test/instrumentation/_agent.js
  test/instrumentation/github-issue-75.js
  test/instrumentation/index.js
  test/instrumentation/modules/http/sse.js
  test/instrumentation/span.js
  test/instrumentation/transaction.js
  test/script/cli.js
Labels: [zube]: In Review, breaking change, enhancement

#661 feat(transaction): add ensureParentId
  docs/transaction-api.asciidoc
  lib/instrumentation/trace-context.js
  lib/instrumentation/transaction.js
  test/instrumentation/trace-context.js
Labels: [zube]: In Review, enhancement

#668 docs: bump minimum supported version of APM Server
  README.md
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review, docs

#672 docs: update links for v2
  docs/agent-api.asciidoc
Labels: docs

#670 chore: depend on elastic-apm-http-client@^6.0.0
  package.json
Labels: [zube]: In Review

#674 fix(async_hooks): more reliable cleanup
  lib/instrumentation/async-hooks.js
Labels: [zube]: In Review, bug, context propagation, performance

#679 perf: improve Async Hooks implementation
  lib/instrumentation/async-hooks.js
Labels: [zube]: In Review

#647 refactor(debug): add parent and trace ids to debug output
  lib/instrumentation/index.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
Labels: [zube]: In Progress

#671 fix: output APM Server error messages
  lib/config.js
Labels: [zube]: In Review

#678 test: fix possible race condition
  test/agent.js
Labels: [zube]: In Review

#680 docs: update transaction.ensureParentId() code example
  docs/transaction-api.asciidoc
Labels: [zube]: In Review

#681 fix: improve APM Server error message in case of 404
  lib/config.js
Labels: [zube]: In Review

#682 docs: update Travis build badge for 2.x to point to 2.x
  README.md
Labels: [zube]: In Review

#692 fix: log APM Server API errors correctly
  lib/config.js
Labels: [zube]: In Review

#695 Docs: Update agent introductions
  docs/intro.asciidoc
Labels: docs

#697 docs: improve debug documentation
  docs/troubleshooting.asciidoc
Labels: [zube]: In Review

#687 docs: fix APM Server links to 6.4
  README.md
  docs/agent-api.asciidoc
  docs/compatibility.asciidoc
  docs/intro.asciidoc
Labels: [zube]: In Review, docs

#694 test(finalhandler): add finalhandler to tav test-matrix
  .travis.yml
  test/.jenkins_tav.yml
Labels: [zube]: In Review

#699 docs: add redirects file
  docs/index.asciidoc
  docs/redirects.asciidoc
Labels: docs
