Repository elastic/apm-agent-nodejs, pull requests merged in 2018-07, with the labels that each got.

#426 test: make schema integration tests more resilient
  test/integration/api-schema/download-json-schemas.sh
Labels: [zube]: In Review

#427 test: don't test knex on unsupported Node versions
  .tav.yml
  package.json
  test/instrumentation/modules/pg/knex.js
Labels: [zube]: In Review

#429 fix: ensure correct streaming when using mimic-response
  .tav.yml
  .travis.yml
  lib/instrumentation/index.js
  lib/instrumentation/modules/mimic-response.js
  lib/instrumentation/shimmer.js
  package.json
  test/.jenkins_tav.yml
  test/instrumentation/modules/http/github-423.js
  test/instrumentation/modules/mimic-response.js
Labels: [zube]: In Review

#435 chore: ensure rogue node_modules folders aren't published
  .npmignore
Labels: [zube]: In Review

#433 test: reduce likelihood of flaky mysql test failing
  test/instrumentation/modules/mysql/mysql.js
Labels: [zube]: In Review

#432 chore: change npm badge in README.md
  README.md
Labels: [zube]: In Review, docs

#430 test: don't patch Module.prototype.require more than once
  lib/instrumentation/index.js
  package.json
  test/_agent.js
Labels: [zube]: In Progress, in progress

#442 perf: don't patch newer versions of mimic-response
  lib/instrumentation/modules/mimic-response.js
Labels: [zube]: In Review

#446 test: run full npm test command on AppVeyor
  .appveyor.yml
  package.json
Labels: [zube]: In Review

#450 chore: code cleanup
  lib/agent.js
Labels: [zube]: In Review

#451 docs: add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: [zube]: In Review

#452 chore: prefix codecov.yml file with a period
  .codecov.yml
Labels: [zube]: In Review

#449 docs: remove reference to Node 10 incompatibility
  docs/compatibility.asciidoc
Labels: [zube]: In Review

#454 chore: update .npmignore
  .npmignore
Labels: [zube]: In Review

#458 test: remove Node 9 nightly/rc jobs from Travis build matrix
  .travis.yml
Labels: [zube]: In Review, ci

#470 chore: use ES 2015 method definition shorthand
  lib/instrumentation/async-hooks.js
  lib/instrumentation/transaction.js
  test/instrumentation/_agent.js
  test/instrumentation/modules/bluebird/bluebird.js
  test/instrumentation/modules/express-graphql.js
  test/instrumentation/modules/generic-pool.js
  test/instrumentation/modules/graphql.js
  test/instrumentation/modules/http/aborted-requests-enabled.js
  test/instrumentation/modules/mysql/mysql.js
  test/instrumentation/modules/mysql2/mysql.js
  test/instrumentation/modules/pg/knex.js
  test/instrumentation/modules/pg/pg.js
  test/sourcemaps/index.js
Labels: [zube]: In Review

#462 feat(agent): add currentTransaction getter
  docs/agent-api.asciidoc
  lib/agent.js
  test/agent.js
Labels: [zube]: In Review, enhancement

#457 test: use custom Travis CI job names
  .travis.yml
Labels: [zube]: In Review, ci

#444 feat(mssql): instrumentation
  .appveyor.yml
  .tav.yml
  docker-compose.yml
  docs/compatibility.asciidoc
  lib/instrumentation/index.js
  lib/instrumentation/modules/tedious.js
  package.json
  test/instrumentation/modules/tedious.js
Labels: [zube]: In Review, enhancement

#472 test(docker): move docker files into test directory
  .dockerignore
  .npmignore
  test/Dockerfile
  test/docker-compose.yml
  test/script/docker/run_docs.sh
  test/script/docker/run_tests.sh
Labels: [zube]: In Review, ci

#466 test: ensure APM Server 503's are handled
  test/integration/503.js
Labels: [zube]: In Review

#467 test: ensure APM Server socket close is handled
  test/integration/socket-close.js
Labels: [zube]: In Review

#479 test(mssql): fix non-deterministic tests
  test/instrumentation/modules/tedious.js
Labels: [zube]: In Review, ci

#480 doc(troubleshooting): update debug mode instructions
  docs/troubleshooting.asciidoc
Labels: [zube]: In Review, docs

#437 feat(cassandra): instrumentation
  .appveyor.yml
  .tav.yml
  .travis.yml
  docs/compatibility.asciidoc
  lib/instrumentation/index.js
  lib/instrumentation/modules/cassandra-driver.js
  package.json
  test/.jenkins_tav.yml
  test/docker-compose.yml
  test/instrumentation/modules/cassandra/_utils.js
  test/instrumentation/modules/cassandra/cassandra.js
  test/script/appveyor/install-cassandra.ps1
  test/test.js
Labels: [zube]: In Review, enhancement

#481 fix(mssql): prepare identification
  lib/instrumentation/modules/tedious.js
  test/.jenkins_tav.yml
Labels: [zube]: In Review, bug
