Repository elastic/apm-agent-nodejs, pull requests merged in 2018-06, with the labels that each got.

#385 test: fix silent error in lambda tests
  test/_apm_server.js
  test/agent.js
Labels: [zube]: In Review

#353 feat(config): disable instrumentation
  docs/agent-api.asciidoc
  lib/config.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/elasticsearch.js
  lib/instrumentation/modules/express-graphql.js
  lib/instrumentation/modules/express.js
  lib/instrumentation/modules/graphql.js
  lib/instrumentation/modules/handlebars.js
  lib/instrumentation/modules/hapi.js
  lib/instrumentation/modules/http.js
  lib/instrumentation/modules/http2.js
  lib/instrumentation/modules/https.js
  lib/instrumentation/modules/ioredis.js
  lib/instrumentation/modules/knex.js
  lib/instrumentation/modules/koa-router.js
  lib/instrumentation/modules/mongodb-core.js
  lib/instrumentation/modules/mysql.js
  lib/instrumentation/modules/pg.js
  lib/instrumentation/modules/redis.js
  test/config.js
  test/instrumentation/_agent.js
Labels: [zube]: In Review, enhancement

#399 feat(graphql): add support for the upcoming GraphQL v14.x
  .tav.yml
  docs/compatibility.asciidoc
  lib/instrumentation/modules/graphql.js
Labels: [zube]: In Review

#395 test(ci): test Node pre-releases without async hooks
  .travis.yml
Labels: [zube]: In Review

#298 mysql2
  .tav.yml
  .travis.yml
  lib/instrumentation/index.js
  lib/instrumentation/modules/mysql2.js
  package.json
  test/.jenkins_tav.yml
  test/instrumentation/modules/mysql2/_utils.js
  test/instrumentation/modules/mysql2/mysql.js
  test/instrumentation/modules/mysql2/pool-release-1.js
  test/test.js
Labels: [zube]: In Review, enhancement

#397 test(bluebird): more reliable coroutine test
  test/instrumentation/modules/bluebird/_coroutine.js
Labels: [zube]: In Review, ci

#401 chore: don't let greenkeeper ignore get-port and restify
  package.json
Labels: [zube]: In Review

#402 chore: minor/patch bump all dependencies
  package.json
Labels: [zube]: In Review

#400 chore: bump devDependencies
  package.json
Labels: [zube]: In Review

#403 docs: improve disableInstrumentations docs
  docs/agent-api.asciidoc
Labels: [zube]: In Review, docs

#404 test: fix randomly failing Bluebird tests
  test/instrumentation/modules/bluebird/_coroutine.js
Labels: [zube]: In Review

#396 feat(express-queue): retain continuity through express-queue
  .tav.yml
  .travis.yml
  docs/compatibility.asciidoc
  lib/instrumentation/index.js
  lib/instrumentation/modules/express-queue.js
  package.json
  test/.jenkins_tav.yml
  test/config.js
  test/instrumentation/modules/express-queue.js
Labels: [zube]: In Review, bug

#411 docs: improve captureBody documentation
  docs/agent-api.asciidoc
Labels: docs

#413 feat: truncate very long error messages
  docs/agent-api.asciidoc
  lib/config.js
  lib/request.js
  test/config.js
  test/request.js
Labels: [zube]: In Review

#415 docs: add into about the npm pacakge to README.md
  README.md
Labels: [zube]: In Review, docs

#417 chore: bump require-in-the-middle dependency to v3.0.0
  package.json
Labels: [zube]: In Review

#420 docs: fix hardcoded references to APM Server 6.2
  README.md
  docs/agent-api.asciidoc
  docs/compatibility.asciidoc
Labels: [zube]: In Review
