Repository elastic/apm-agent-nodejs, pull requests merged in 2018-03, with the labels that each got.

#258 docs: improve ignoreUserAgents example
  docs/agent-api.asciidoc
Labels: docs

#259 docs: improve addFilter example
  docs/agent-api.asciidoc
Labels: docs

#245 docs: add guide for upgrading from v0.x to v1.x
  docs/index.asciidoc
  docs/upgrade-to-v1.asciidoc
  docs/upgrading.asciidoc
Labels: docs

#270 fix(config): set default maxQueueSize to 100
  docs/agent-api.asciidoc
  lib/config.js
Labels: bug, performance

#238 feat(config): add serverTimeout
  docs/agent-api.asciidoc
  lib/agent.js
  lib/config.js
  lib/request.js
  package.json
  test/config.js
  test/request.js
Labels: enhancement

#269 fix(span): Do not pass stack frames into promises
  lib/instrumentation/span.js
  package.json
Labels: enhancement, performance

#275 docs(readme): improve README.md copy
  README.md
Labels: docs

#286 feat(request): include ppid
  lib/request.js
  test/request.js
Labels: elastic-6.3, enhancement, review

#283 docs: add frameworkVersion example
  docs/agent-api.asciidoc
Labels: docs
