Repository elastic/apm-agent-nodejs, pull requests merged in 2018-10, with the labels that each got.

#604 feat(config): change config order
  docs/agent-api.asciidoc
  lib/config.js
  test/config.js
  test/instrumentation/async-hooks.js
Labels: [zube]: In Review, breaking change, enhancement

#607 test(mongodb): ensure spans are sorted by start time
  test/instrumentation/modules/mongodb-core.js
Labels: [zube]: In Review, ci

#601 feat(config): support byte suffixes
  docs/agent-api.asciidoc
  lib/config.js
  test/config.js
Labels: [zube]: In Review, enhancement

#615 test: fix api schema integration tests
  test/integration/api-schema/basic.js
  test/integration/api-schema/download-json-schemas.sh
Labels: [zube]: In Review

#616 refactor: use new microsecond timestamps
  lib/agent.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/span.js
  lib/instrumentation/timer.js
  lib/instrumentation/transaction.js
  package.json
  test/instrumentation/index.js
  test/instrumentation/modules/elasticsearch.js
  test/instrumentation/modules/express-graphql.js
  test/instrumentation/modules/express-queue.js
  test/instrumentation/modules/graphql.js
  test/instrumentation/modules/http2.js
  test/instrumentation/modules/ioredis.js
  test/instrumentation/modules/mongodb-core.js
  test/instrumentation/modules/redis.js
  test/instrumentation/modules/ws.js
  test/instrumentation/span.js
  test/instrumentation/timer.js
  test/instrumentation/transaction.js
Labels: [zube]: In Review, breaking change

#538 feat: distributed tracing
  docs/agent-api.asciidoc
  lib/agent.js
  lib/instrumentation/async-hooks.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/index.js
  lib/instrumentation/span.js
  lib/instrumentation/trace-context.js
  lib/instrumentation/transaction.js
  test/agent.js
  test/instrumentation/_agent.js
  test/instrumentation/index.js
  test/instrumentation/modules/http/basic.js
  test/instrumentation/modules/http/outgoing.js
  test/instrumentation/span.js
  test/instrumentation/trace-context.js
  test/instrumentation/transaction.js
Labels: [zube]: In Review, enhancement

#618 test: remove unnecessary download of JSON schema
  test/integration/api-schema/download-json-schemas.sh
Labels: [zube]: In Review

#516 feat(ioredis): add support for ioredis version 4.x
  .tav.yml
  docs/compatibility.asciidoc
  lib/instrumentation/modules/ioredis.js
Labels: [zube]: In Review

#619 chore(package): upgrade read-pkg-up to ^4.0.0
  package.json
Labels: [zube]: In Review

#623 chore(package): bump all dev-dependencies to newest minor
  package.json
Labels: [zube]: In Review

#613 feat(config): stricter boolean parsing
  .travis.yml
  lib/config.js
  package.json
  test/config.js
Labels: [zube]: In Review, breaking change, enhancement

#622 chore(package): bump dev-dependencies to newest major
  package.json
Labels: [zube]: In Review

#621 chore(package): unpin dev-dependency express-queue
  package.json
Labels: [zube]: In Review

#602 feat(config): support time suffixes
  docs/agent-api.asciidoc
  lib/config.js
  lib/instrumentation/http-shared.js
  test/config.js
  test/instrumentation/_agent.js
  test/instrumentation/modules/http/aborted-requests-enabled.js
  test/integration/no-sampling.js
Labels: [zube]: In Review, breaking change, enhancement

#620 chore(package): bump all dependencies to newest minor
  package.json
Labels: [zube]: In Review

#631 docs: add v2 upgrade guide
  docs/upgrade-to-v2.asciidoc
  docs/upgrading.asciidoc
Labels: [zube]: In Review, docs

#635 Fix documentation spelling and grammatical errors
  docs/agent-api.asciidoc
  docs/api.asciidoc
  docs/custom-spans.asciidoc
  docs/custom-stack.asciidoc
  docs/express.asciidoc
  docs/hapi.asciidoc
  docs/intro.asciidoc
  docs/koa.asciidoc
  docs/lambda.asciidoc
  docs/performance-tuning.asciidoc
  docs/restify.asciidoc
  docs/setup.asciidoc
  docs/span-api.asciidoc
  docs/troubleshooting.asciidoc
  docs/upgrading.asciidoc
Labels: docs

#638 docs: add note about typescript import
  docs/agent-api.asciidoc
Labels: [zube]: In Review, docs

#634 feat(shimmer): safely handle property descriptors
  lib/instrumentation/patch-async.js
  lib/instrumentation/shimmer.js
Labels: [zube]: In Review, bug

#639 docs: improve custom transactions example
  docs/custom-transactions.asciidoc
Labels: [zube]: In Review, docs

#637 fix(http): bind writeHead to transaction
  lib/instrumentation/http-shared.js
  lib/instrumentation/modules/http.js
  lib/symbols.js
  test/instrumentation/modules/http/bind-write-head-to-transaction.js
Labels: [zube]: In Review, bug

#636 feat(agent): return uuid in captureError callback
  docs/agent-api.asciidoc
  lib/agent.js
  test/agent.js
Labels: [zube]: In Review, enhancement

#646 test(express-graphql): update test and patch ranges to match
  .tav.yml
  lib/instrumentation/modules/express-graphql.js
Labels: [zube]: In Review, ci
