Repository elastic/apm-agent-nodejs, pull requests merged in 2018-02, with the labels that each got.

#240 fix(express): prevent invalid errors from reporting
  lib/instrumentation/modules/express.js
  test/instrumentation/modules/express.js
Labels: bug, review

#220 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: docs

#248 docs: fix error in doc text
  docs/custom-stack.asciidoc
  docs/express.asciidoc
  docs/hapi.asciidoc
  docs/koa.asciidoc
Labels: docs

#249 test(travis): only run tav tests on PR's and cron jobs
  .travis.yml
Labels: ci
