Repository elastic/apm-agent-nodejs, pull requests merged in 2018-08, with the labels that each got.

#483 test: refactor how to run tests locally
  .appveyor.yml
  .npmignore
  CONTRIBUTING.md
  TESTING.md
  package.json
  test/docker-compose.ci.yml
  test/docker-compose.yml
  test/posttest.sh
  test/pretest.sh
  test/script/docker/run_tests.sh
  test/script/local-deps-start.sh
  test/script/local-deps-stop.sh
  test/script/run_tests.sh
Labels: [zube]: In Review

#489 test(appveyor): abort tests if install scripts fail
  test/script/appveyor/install-cassandra.ps1
  test/script/appveyor/install-elasticsearch.ps1
  test/script/appveyor/install-redis.ps1
Labels: [zube]: In Review

#491 test(http): improve http abort tests
  test/instrumentation/modules/http/aborted-requests-disabled.js
Labels: [zube]: In Review, ci

#492 perf: improve request body parsing speed
  lib/parsers.js
  test/parsers.js
Labels: [zube]: In Review

#490 test(api-schema): fix to support paths with spaces
  test/instrumentation/modules/http/_echo_server_util.js
  test/integration/api-schema/_utils.js
Labels: [zube]: In Review, ci

#495 test(got): fix tests for got@9.0.0
  .tav.yml
  package.json
  test/instrumentation/modules/http/github-423.js
Labels: [zube]: In Progress

#501 docs: add PR links to CHANGELOG.md
  CHANGELOG.md
Labels: [zube]: In Review, docs

#496 docs: fix 404 link in README.md
  README.md
Labels: [zube]: In Review, docs

#497 docs: use relative links in markdown files
  CONTRIBUTING.md
  README.md
  TESTING.md
Labels: [zube]: In Review, docs

#493 test(hapi): reenable for 10.8+
  test/instrumentation/modules/hapi.js
Labels: [zube]: In Review, ci

#503 fix: ensure logger config can update
  lib/agent.js
  lib/config.js
Labels: [zube]: In Review, bug

#504 test: properly exclude failing version
  test/instrumentation/modules/hapi.js
Labels: [zube]: In Review, bug, ci

#505 test: fix agent lambda tests when run with nyc
  test/agent.js
Labels: [zube]: In Review

#485 feat(filters): filter set-cookie headers
  lib/filters.js
  package.json
  test/filters.js
Labels: [zube]: In Review, enhancement

#521 fix(tests): api-schema has a new tags file
  test/integration/api-schema/download-json-schemas.sh
Labels: [zube]: In Review, ci

#520 chore: update debug message to match reality
  lib/instrumentation/index.js
Labels: [zube]: In Review

#508 feat(config): default serviceName to package name
  docs/agent-api.asciidoc
  lib/config.js
  package.json
  test/config.js
Labels: [zube]: In Review, enhancement

#527 test: don't swallow errors in Restify tests
  test/instrumentation/modules/restify.js
Labels: [zube]: In Review

#532 test: do not capture exceptions in disableInstrumentations test
  test/config.js
Labels: [zube]: In Review, ci

#537 fix: always call agent.flush() callback
  lib/instrumentation/index.js
  test/agent.js
Labels: [zube]: In Review

#536 perf: declare instance properties in constructor
  lib/agent.js
  lib/instrumentation/index.js
Labels: [zube]: In Review

#534 test: bump standard to version ^12.0.1
  lib/agent.js
  lib/instrumentation/async-hooks.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/elasticsearch.js
  lib/instrumentation/modules/graphql.js
  lib/instrumentation/modules/mysql.js
  lib/instrumentation/modules/mysql2.js
  lib/instrumentation/modules/pg.js
  lib/instrumentation/patch-async.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  lib/parsers.js
  package.json
  test/_apm_server.js
  test/agent.js
  test/config.js
  test/instrumentation/index.js
  test/instrumentation/modules/bluebird/bluebird.js
  test/instrumentation/modules/bluebird/cancel.js
  test/instrumentation/modules/elasticsearch.js
  test/instrumentation/modules/express-graphql.js
  test/instrumentation/modules/generic-pool.js
  test/instrumentation/modules/graphql.js
  test/instrumentation/modules/http/_echo_server.js
  test/instrumentation/modules/http/aborted-requests-enabled.js
  test/instrumentation/modules/http/github-179.js
  test/instrumentation/modules/http/outgoing.js
  test/instrumentation/modules/http/sse.js
  test/instrumentation/modules/http2.js
  test/instrumentation/modules/koa-router/index.js
  test/instrumentation/modules/mimic-response.js
  test/instrumentation/modules/mongodb-core.js
  test/instrumentation/modules/mysql/_utils.js
  test/instrumentation/modules/mysql/mysql.js
  test/instrumentation/modules/mysql2/_utils.js
  test/instrumentation/modules/mysql2/mysql.js
  test/instrumentation/modules/pg/_utils.js
  test/instrumentation/modules/pg/pg.js
  test/instrumentation/modules/ws.js
  test/instrumentation/transaction.js
  test/integration/api-schema/_utils.js
  test/integration/api-schema/basic.js
  test/parsers.js
  test/request.js
  test/sourcemaps/index.js
  test/start/env/test.js
  test/start/file/test.js
Labels: [zube]: In Review

#542 test: fix linter error
  test/agent.js
Labels: [zube]: In Review

#541 test: fix flaky `disableInstrumentations` tests
  test/_agent.js
  test/config.js
Labels: [zube]: In Review

#543 fix: override empty serviceName with package name
  lib/config.js
Labels: [zube]: In Review

#546 docs: add # in front of PR numbers in CHANGELOG.md
  CHANGELOG.md
Labels: [zube]: In Review
