Repository elastic/apm-agent-nodejs, pull requests merged in 2018-04, with the labels that each got.

#234 feat(lambda): implement manual lambda instrumentation
  docs/agent-api.asciidoc
  docs/index.asciidoc
  docs/lambda.asciidoc
  lib/agent.js
  test/_apm_server.js
  test/_assert.js
  test/agent.js
  test/instrumentation/span.js
  test/instrumentation/transaction.js
Labels: enhancement, review

#296 fix(doc): lambda getting started had old argument
  docs/lambda.asciidoc
Labels: [zube]: In Review, bug

#301 fix(test): appName -> serviceName in http test
  test/instrumentation/modules/http/github-179.js
Labels: [zube]: In Review, review

#299 fix(config): restore custom logger feature
  docs/agent-api.asciidoc
  lib/agent.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/bluebird.js
  lib/instrumentation/modules/elasticsearch.js
  lib/instrumentation/modules/express-graphql.js
  lib/instrumentation/modules/express.js
  lib/instrumentation/modules/generic-pool.js
  lib/instrumentation/modules/graphql.js
  lib/instrumentation/modules/handlebars.js
  lib/instrumentation/modules/hapi.js
  lib/instrumentation/modules/http.js
  lib/instrumentation/modules/https.js
  lib/instrumentation/modules/ioredis.js
  lib/instrumentation/modules/knex.js
  lib/instrumentation/modules/koa-router.js
  lib/instrumentation/modules/mongodb-core.js
  lib/instrumentation/modules/mysql.js
  lib/instrumentation/modules/pg.js
  lib/instrumentation/modules/redis.js
  lib/instrumentation/modules/ws.js
  lib/instrumentation/shimmer.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  lib/logger.js
  lib/parsers.js
  lib/queue.js
  lib/request.js
  package.json
  test/instrumentation/_agent.js
  test/instrumentation/index.js
  test/parsers.js
  test/queue.js
Labels: [zube]: In Review, bug, review

#302 docs: document how to add support for new modules
  CONTRIBUTING.md
Labels: [zube]: In Review
