Repository elastic/apm-agent-nodejs, pull requests merged in 2018-09, with the labels that each got.

#548 chore: pin wait-on@2.1.0
  package.json
Labels: [zube]: In Review

#550 chore: un-pin wait-on devDependency
  package.json
Labels: [zube]: In Review

#554 test: fix testing for process version
  test/agent.js
Labels: [zube]: In Review

#566 refactor: convert maxQueueSize -1 to Infinity at boot
  lib/config.js
  lib/queue.js
  test/config.js
Labels: [zube]: In Review

#553 feat(transaction): span_count.total
  lib/instrumentation/transaction.js
  test/instrumentation/transaction.js
Labels: [zube]: In Progress, enhancement

#570 chore(docs): move build_docs.sh script under docs folder
  .npmignore
  docs/scripts/build_docs.sh
  package.json
  test/script/docker/run_docs.sh
Labels: [zube]: In Review, docs

#565 docs: show correct type for disableInstrumentations options
  docs/agent-api.asciidoc
Labels: [zube]: In Review

#567 fix: default transactionMaxSpans to 500
  docs/agent-api.asciidoc
  lib/config.js
  test/config.js
Labels: [zube]: In Progress

#569 test: add tests for missing config options
  test/config.js
Labels: [zube]: In Progress

#558 Stalling `npm install` workaround + cache node modules
  .travis.yml
Labels: ci

#580 fix: don't fail if captureError callback isn't provided
  lib/agent.js
  test/agent.js
Labels: [zube]: In Review, bug

#581 test: update intake API endpoint path
  test/_apm_server.js
  test/agent.js
  test/integration/server-url-path.js
Labels: [zube]: In Review, ci

#585 test: re-enable schema tests for the v2 api
  lib/instrumentation/span.js
  test/instrumentation/span.js
  test/integration/api-schema/_utils.js
  test/integration/api-schema/basic.js
  test/integration/api-schema/capture-error-log-stack-traces.js
  test/integration/api-schema/capture-span-stack-traces.js
  test/integration/api-schema/download-json-schemas.sh
  test/integration/api-schema/source-lines-error-frames.js
  test/integration/api-schema/source-lines-span-frames.js
  test/test.js
Labels: [zube]: In Review

#587 test: fix json schema tests
  test/integration/api-schema/basic.js
Labels: [zube]: In Review

#589 fix: v2 schema tests
  test/integration/api-schema/basic.js
Labels: [zube]: In Review, ci

#590 test(schema): cleanup schema checkout if download fails
  test/integration/api-schema/_utils.js
Labels: [zube]: In Review, ci

#595 docs: improve intro docs
  docs/intro.asciidoc
Labels: [zube]: In Review, docs

#596 docs: fix overwrite vs override grammar
  docs/agent-api.asciidoc
  docs/custom-stack.asciidoc
  docs/express.asciidoc
  docs/hapi.asciidoc
  docs/koa.asciidoc
  docs/lambda.asciidoc
  docs/restify.asciidoc
  docs/setup.asciidoc
Labels: [zube]: In Review, docs

#597 docs: update ToC in README.md with missing topics
  README.md
Labels: [zube]: In Review, docs

#598 docs: fix typo
  docs/custom-stack.asciidoc
Labels: [zube]: In Review, docs

#599 fix(ws): allow disabling
  lib/instrumentation/modules/ws.js
Labels: [zube]: In Review, bug
