Repository elastic/apm-agent-nodejs, pull requests merged in 2018-05, with the labels that each got.

#321 fix: encode spans even if their stack trace can't be captured
  lib/instrumentation/span.js
Labels: [zube]: In Review

#319 refactor: update comments to reflect reality
  lib/instrumentation/index.js
Labels: [zube]: In Review

#320 perf: use constant to store test boolean
  lib/instrumentation/span.js
Labels: [zube]: In Review

#324 test: improve test output for parsers.prepareCallsite()
  test/parsers.js
Labels: [zube]: In Review

#317 feat(transaction): add toJSON to transaction
  lib/instrumentation/transaction.js
Labels: [zube]: In Review, enhancement, review

#313 feat(transaction): add addTags method
  docs/agent-api.asciidoc
  lib/agent.js
  lib/instrumentation/transaction.js
  test/instrumentation/transaction.js
Labels: [zube]: In Review, enhancement, review

#329 chore: ignore .vscode directory
  .gitignore
Labels: [zube]: In Review, review

#328 feat(transaction): call end with result
  docs/agent-api.asciidoc
  docs/transaction-api.asciidoc
  lib/instrumentation/transaction.js
  test/instrumentation/transaction.js
Labels: [zube]: In Review, enhancement, review

#327 doc: release process instructions
  CONTRIBUTING.md
Labels: [zube]: In Review, docs, review

#332 docs: improve npm release guidelines
  CONTRIBUTING.md
Labels: review

#344 docs: add elasticsearch-js to list of instrumented modules
  docs/compatibility.asciidoc
Labels: docs

#205 feat(http2): instrument incoming http2 requests
  lib/instrumentation/index.js
  lib/instrumentation/modules/http2.js
  lib/parsers.js
  test/instrumentation/modules/http2.js
Labels: [zube]: In Review, enhancement, review

#351 test(agent): add tests for agent.setTransactionName()
  test/agent.js
Labels: [zube]: In Review

#348 test(agent): test agent.addFilter() with invalid argument
  test/agent.js
Labels: [zube]: In Review

#352 chore: update devDependencies with known security vulnerabilities
  package.json
  test/script/cli.js
Labels: [zube]: In Review

#347 test(agent): add tests for agent.addTags()
  test/agent.js
Labels: [zube]: In Review

#349 test(agent): add test for agent.startTransaction()
  test/agent.js
Labels: [zube]: In Review

#350 fix(agent): allow agent.endTransaction() to set result
  lib/instrumentation/index.js
  test/agent.js
Labels: [zube]: In Review

#355 test(http2): fix broken tests on new Node v8.11.2 release
  test/instrumentation/modules/http2.js
Labels: [zube]: In Review

#357 docs: add link to lambda docs from custom stack docs
  docs/custom-stack.asciidoc
Labels: [zube]: In Review, docs

#359 test: allow test suite to run against Node.js release candidates
  test/instrumentation/modules/hapi.js
  test/instrumentation/modules/http2.js
Labels: [zube]: In Review

#364 test(ci): use conditional stages to quicker skip builds
  .travis.yml
Labels: [zube]: In Review

#366 test: test that unsampled http transactions have the expected result
  test/instrumentation/index.js
Labels: [zube]: In Review

#338 test: schema validate payload sent to APM Server
  package.json
  test/integration/api-schema/_utils.js
  test/integration/api-schema/basic.js
  test/integration/api-schema/capture-error-log-stack-traces.js
  test/integration/api-schema/capture-span-stack-traces.js
  test/integration/api-schema/download-json-schemas.sh
  test/integration/api-schema/source-lines-error-frames.js
  test/integration/api-schema/source-lines-span-frames.js
  test/test.js
Labels: [zube]: In Review

#374 test: un-pin devDependency
  package.json
Labels: [zube]: In Review

#370 test(ci): test unreleased versions of Node.js
  .travis.yml
  README.md
Labels: [zube]: In Review

#377 docs(span): reference apm.startSpan() over span.start()
  docs/span-api.asciidoc
Labels: [zube]: In Review, docs

#371 fix(instrumentation): add bindEmitter for requests
  lib/instrumentation/http-shared.js
  lib/instrumentation/index.js
  lib/instrumentation/shimmer.js
  package.json
  test/instrumentation/index.js
  test/instrumentation/modules/http/request.js
Labels: [zube]: In Review, enhancement, review

#326 feat(http2): instrument client requests
  lib/instrumentation/modules/http2.js
  test/instrumentation/modules/http2.js
Labels: [zube]: In Review, enhancement, review

#380 chore: don't use "anonymous" functions
  lib/request.js
Labels: [zube]: In Review

#379 docs: fix asciidoc table syntax to match general style
  docs/upgrade-to-v1.asciidoc
Labels: [zube]: In Review

#384 fix: get remoteAddress before req close event
  lib/instrumentation/transaction.js
Labels: [zube]: In Review

#383 test: improve tape output for easier debugging
  test/instrumentation/modules/http2.js
Labels: [zube]: In Review

#381 test: ensure tests don't wait for queue timeout
  test/instrumentation/modules/http2.js
Labels: [zube]: In Review
