Repository elastic/apm-agent-nodejs, pull requests merged in 2019-01, with the labels that each got.

#767 feat: include sampled flag on errors
  lib/agent.js
  test/agent.js
Labels: [zube]: In Review, enhancement

#770 test(schema): improve reliability
  test/integration/api-schema/_utils.js
  test/integration/api-schema/basic.js
  test/integration/api-schema/download-json-schemas.sh
Labels: [zube]: In Review, ci

#763 [1.x] test(ci): fix apollo-server-express tests on older Node versions (#743)
  test/instrumentation/modules/apollo-server-express.js
Labels: [zube]: In Review, backport

#775 fix(tedious): don't fail on newest tedious v4.1.3
  lib/instrumentation/modules/tedious.js
Labels: [zube]: In Review

#776 chore(package): bump dev dependency ioredis to ^4.3.0
  package.json
Labels: [zube]: In Review

#777 docs: update supported version range of tedious
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review, docs

#792 fix: we don't support mongodb-core v3.1.10+
  .tav.yml
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/mongodb-core.js
  package.json
Labels: [zube]: In Review

#795 feat(config): validate serverUrl port
  lib/agent.js
Labels: [zube]: In Review, enhancement

#799 fix: filter outgoing http headers with any case
  lib/filters/http-headers.js
Labels: [zube]: In Review

#805 feat: add transaction.type to errors
  lib/agent.js
  test/agent.js
Labels: [zube]: In Review, enhancement

#800 [1.x] fix: we don't support mongodb-core v3.1.10+ (#792)
  .tav.yml
  docs/compatibility.asciidoc
  lib/instrumentation/modules/mongodb-core.js
  package.json
Labels: [zube]: In Review, backport

#761 [1.x] fix(graphql): don't throw on invalid query (#747)
  lib/instrumentation/modules/graphql.js
  test/instrumentation/modules/graphql.js
Labels: [zube]: In Review, backport

#814 fix: ensure request.url.port is a string on transactions
  lib/instrumentation/transaction.js
Labels: [zube]: In Progress

#766 feat(config): add container info options
  docs/configuration.asciidoc
  lib/config.js
  package.json
  test/config.js
Labels: [zube]: In Review, enhancement

#783 docs: added NOTICE file
  NOTICE.md
Labels: [zube]: In Review, enhancement

#788 feat(config): add captureHeaders config
  docs/configuration.asciidoc
  lib/agent.js
  lib/config.js
  lib/instrumentation/transaction.js
  lib/parsers.js
  test/instrumentation/_agent.js
  test/parsers.js
Labels: [zube]: In Progress, enhancement

#820 fix(parsers): move port fix into parser
  lib/instrumentation/transaction.js
  lib/parsers.js
  test/instrumentation/modules/hapi.js
  test/parsers.js
Labels: [zube]: In Review, bug

#818 feat: add support for custom start/end times
  docs/agent-api.asciidoc
  docs/span-api.asciidoc
  docs/transaction-api.asciidoc
  lib/agent.js
  lib/instrumentation/generic-span.js
  lib/instrumentation/index.js
  lib/instrumentation/span.js
  lib/instrumentation/timer.js
  lib/instrumentation/transaction.js
  test/agent.js
  test/instrumentation/span.js
  test/instrumentation/timer.js
  test/instrumentation/transaction.js
Labels: [zube]: In Review

#822 refactor: change order of args to GenericSpan
  lib/instrumentation/generic-span.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
Labels: [zube]: In Review

#825 fix: don't ignore custom trace context on spans
  lib/instrumentation/span.js
Labels: [zube]: In Review

#823 feat: add ability to set custom timestamp for errors
  docs/agent-api.asciidoc
  lib/agent.js
  test/agent.js
Labels: [zube]: In Review

#824 feat: add ability to set custom log message for errors
  docs/agent-api.asciidoc
  lib/agent.js
  test/agent.js
Labels: [zube]: In Review

#826 refactor: simplify API for resuming traces
  docs/agent-api.asciidoc
  lib/instrumentation/generic-span.js
  lib/instrumentation/index.js
  lib/instrumentation/span.js
  lib/instrumentation/trace-context.js
  lib/instrumentation/transaction.js
  test/agent.js
  test/instrumentation/span.js
  test/instrumentation/trace-context.js
  test/instrumentation/transaction.js
Labels: [zube]: In Review

#821 refactor: remove sampled property alias from trace context
  lib/instrumentation/generic-span.js
  lib/instrumentation/trace-context.js
  test/instrumentation/trace-context.js
Labels: [zube]: In Review

#828 docs: add OpenTracing docs
  docs/index.asciidoc
  docs/opentracing.asciidoc
Labels: [zube]: In Review, docs

#731 feat(metrics): added basic metrics gathering
  NOTICE.md
  docs/configuration.asciidoc
  docs/index.asciidoc
  docs/metrics.asciidoc
  lib/agent.js
  lib/config.js
  lib/metrics/index.js
  lib/metrics/platforms/generic/index.js
  lib/metrics/platforms/generic/process-cpu.js
  lib/metrics/platforms/generic/process-top.js
  lib/metrics/platforms/generic/system-cpu.js
  lib/metrics/platforms/linux/index.js
  lib/metrics/platforms/linux/stats.js
  lib/metrics/registry.js
  lib/metrics/reporter.js
  package.json
  test/_agent.js
  test/agent.js
  test/instrumentation/_agent.js
  test/instrumentation/modules/http/github-423.js
  test/integration/allow-invalid-cert.js
  test/integration/api-schema/basic.js
  test/integration/api-schema/capture-error-log-stack-traces.js
  test/integration/api-schema/capture-span-stack-traces.js
  test/integration/api-schema/source-lines-error-frames.js
  test/integration/api-schema/source-lines-span-frames.js
  test/metrics/index.js
Labels: [zube]: In Review, enhancement

#832 [docs] Fix 404 node release schedule image
  docs/images/node_release_schedule.png
  docs/supported-technologies.asciidoc
Labels: docs
