Repository elastic/apm-agent-nodejs, pull requests merged in 2019-11, with the labels that each got.

#1497 fix(knex): make stack traces work in 0.18+
  lib/instrumentation/modules/knex.js
  lib/instrumentation/shimmer.js
  test/instrumentation/modules/pg/knex.js
Labels: [zube]: In Review, bug

#1498 feat(config): add serviceNodeName
  docs/configuration.asciidoc
  lib/config.js
  package.json
  test/config.js
Labels: [zube]: In Review, elastic-7.5, enhancement

#1500 [2.x] fix(knex): make stack traces work in 0.18+ (#1497)
  lib/instrumentation/modules/knex.js
  lib/instrumentation/shimmer.js
Labels: backport

#1503 [docs] fix pull link
  docs/release-notes.asciidoc
Labels: backport:2.x, docs

#1501 chore: update GitHub PR template
  .github/pull_request_template.md
Labels: [zube]: In Review

#1513 docs: deprecate lambda support
  docs/lambda.asciidoc
  docs/set-up.asciidoc
Labels: backport:2.x, docs

#1514 [2.x] docs: deprecate lambda (#1513)
  docs/lambda.asciidoc
  docs/set-up.asciidoc
Labels: backport

#1523 fix(ioredis): prevent unhandled promise rejection
  lib/instrumentation/modules/ioredis.js
  test/instrumentation/modules/ioredis.js
Labels: backport:2.x

#1522 ci(jenkins): update argument
  .ci/Jenkinsfile
Labels: automation

#1525 [jjbb] check_paths_for_matches.py not required anymore
  .ci/bin/check_paths_for_matches.py
Labels: automation, ci

#1528 ci(jenkins): update argument (#1522)
  .ci/Jenkinsfile
Labels: automation, ci

#1526 ci(jenkins) Add Jenkins badge for 2.x branch
  README.md
Labels: automation, ci

#1527 ci(jenkins) Update CI badges
  README.md
Labels: automation, ci

#1531 fix(package): bump elastic-apm-http-client to ^9.2.1
  package.json
Labels: [zube]: In Review

#1540 ci(travis): don't update npm to latest version
  .travis.yml
Labels: [zube]: In Review

#1533 fix(package): bump end-of-stream to ^1.4.4
  package.json
Labels: [zube]: In Review

#1536 fix(package): bump shallow-clone-shim to ^2.0.0
  package.json
Labels: [zube]: In Review

#1535 fix(package): bump semver to ^6.3.0
  package.json
Labels: [zube]: In Review

#1534 chore(package): bump all dev-dependencies
  package.json
Labels: [zube]: In Review

#1541 docs: document commit message guidelines
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: [zube]: In Review

#1539 ci(jenkins): Use 3.x branch for CI badges
  README.md
Labels: automation, ci

#1544 fix(package): bump require-in-the-middle to ^5.0.2
  package.json
Labels: [zube]: In Review

#1549 ci(jenkins): add memcached to edge tests
  .ci/docker/docker-compose-edge.yml
Labels: automation, bug
