Repository elastic/apm-agent-nodejs, pull requests merged in 2019-03, with the labels that each got.

#882 test: be more relaxed with minimum duration
  test/agent.js
  test/instrumentation/span.js
  test/instrumentation/timer.js
  test/instrumentation/transaction.js
Labels: [zube]: In Review

#891 test(restify): only run tests of v8+ on Node.js 8+
  .tav.yml
  package.json
Labels: [zube]: In Review

#884 chore(package): bump cassandra-driver dev dependency to ^4.0.0
  package.json
Labels: [zube]: In Review

#889 chore(package): bump tedious dev dependency to ^5.0.3
  package.json
  test/instrumentation/modules/tedious.js
Labels: [zube]: In Review

#894 docs: add missing ToC links to README.md
  README.md
Labels: [zube]: In Review, docs

#893 chore(package): bump graphql + express-graphql dev dependencies
  package.json
Labels: [zube]: In Review

#883 test(cassandra): refactor test files
  .tav.yml
  test/instrumentation/modules/cassandra-driver/_utils.js
  test/instrumentation/modules/cassandra-driver/index.js
  test/test.js
Labels: [zube]: In Review

#594 feat: add support for Fastify
  .tav.yml
  .travis.yml
  README.md
  docs/agent-api.asciidoc
  docs/custom-stack.asciidoc
  docs/fastify.asciidoc
  docs/index.asciidoc
  docs/intro.asciidoc
  docs/supported-technologies.asciidoc
  lib/instrumentation/index.js
  lib/instrumentation/modules/fastify.js
  package.json
  test/.jenkins_tav.yml
  test/instrumentation/modules/fastify/_async-await.js
  test/instrumentation/modules/fastify/async-await.js
  test/instrumentation/modules/fastify/fastify.js
  test/test.js
Labels: [zube]: In Review

#895 chore(package): bump elastic-apm-http-client to ^7.1.1
  package.json
Labels: [zube]: In Review

#901 test: fix race condition in custom transport test
  test/config.js
Labels: [zube]: In Review

#898 fix: add missing 'use strict' declarations
  lib/lambda.js
  lib/metrics/platforms/linux/index.js
  lib/metrics/platforms/linux/stats.js
  test/instrumentation/modules/cassandra-driver/_utils.js
  test/lambda/_util.js
  test/lambda/callbacks.js
  test/lambda/context.js
  test/lambda/mock/agent.js
  test/lambda/mock/transaction.js
  test/lambda/promises.js
  test/start/file/elastic-apm-node.js
  test/test.js
Labels: [zube]: In Review

#919 test: fix intake API integration test
  test/integration/api-schema/basic.js
Labels: [zube]: In Review

#918 chore: make Agent method signatures more explicit
  lib/agent.js
Labels: [zube]: In Review

#764 test: ensure squashed commit messages doesn't exceed limit
  package.json
Labels: [zube]: In Review

#915 test(fastify): bump fastify dev dependency to ^2.0.1
  package.json
Labels: [zube]: In Review

#922 fix: bind the agent.flush callback
  lib/agent.js
Labels: [zube]: In Review

#924 Docs: fix rendering of table
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review, docs

#928 ci(jenkins) use current as pipeline shared library version
  Jenkinsfile
Labels: automation

#933 chore(package): update measured-reporting to 1.41.0
  package.json
Labels: [zube]: In Review, bug

#934 fix(agent): allow flush callback to be undefined
  lib/agent.js
Labels: [zube]: In Review

#912 fix(metrics): use noop logger in metrics reporter
  lib/metrics/index.js
  test/config.js
Labels: [zube]: In Review

#931 fix(lambda): do not wrap context
  lib/lambda.js
Labels: [zube]: In Review, bug

#936 fix(transaction): don't set transaction result of it's null
  lib/instrumentation/transaction.js
Labels: [zube]: In Review

#803 feat(instrumentation): add patch registry
  docs/agent-api.asciidoc
  lib/agent.js
  lib/config.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/apollo-server-core.js
  lib/instrumentation/modules/bluebird.js
  lib/instrumentation/modules/cassandra-driver.js
  lib/instrumentation/modules/elasticsearch.js
  lib/instrumentation/modules/express-graphql.js
  lib/instrumentation/modules/express-queue.js
  lib/instrumentation/modules/express.js
  lib/instrumentation/modules/fastify.js
  lib/instrumentation/modules/generic-pool.js
  lib/instrumentation/modules/graphql.js
  lib/instrumentation/modules/handlebars.js
  lib/instrumentation/modules/hapi.js
  lib/instrumentation/modules/http.js
  lib/instrumentation/modules/http2.js
  lib/instrumentation/modules/https.js
  lib/instrumentation/modules/ioredis.js
  lib/instrumentation/modules/knex.js
  lib/instrumentation/modules/koa-router.js
  lib/instrumentation/modules/koa.js
  lib/instrumentation/modules/mimic-response.js
  lib/instrumentation/modules/mongodb-core.js
  lib/instrumentation/modules/mysql.js
  lib/instrumentation/modules/mysql2.js
  lib/instrumentation/modules/pg.js
  lib/instrumentation/modules/redis.js
  lib/instrumentation/modules/restify.js
  lib/instrumentation/modules/tedious.js
  lib/instrumentation/modules/ws.js
  lib/instrumentation/named-array.js
  test/_patch.js
  test/agent.js
  test/config.js
Labels: [zube]: In Review, enhancement

#943 fix: don't return anything from the module patch functions
  lib/instrumentation/index.js
Labels: [zube]: In Review

#926 chore: add TypeScript typings file
  .gitignore
  .tav.yml
  docs/setup.asciidoc
  docs/supported-technologies.asciidoc
  index.d.ts
  package.json
  start.d.ts
  test/babel/.babelrc
  test/babel/src.js
  test/esm/index.mjs
  test/script/run_tests.sh
  test/types/commonjs.js
  test/types/index.ts
  test/types/start.ts
  test/types/transpile/index.ts
  test/types/transpile/tsconfig.json
  test/types/tsconfig.json
Labels: [zube]: In Review

#942 chore(npm): add missing files to .npmignore
  .npmignore
Labels: [zube]: In Review

#944 chore: improve 'npm run' command namespaces
  TESTING.md
  package.json
  test/script/docker/run_tests.sh
  test/script/run_tests.sh
Labels: [zube]: In Review

#946 chore(npm): don't include Jenkinsfile in npm build
  .npmignore
Labels: [zube]: In Review

#947 fix(package): bump elastic-apm-http-client to ^7.1.2
  package.json
Labels: [zube]: In Review

#952 fix: don't add traceparent header to S3 requests
  lib/instrumentation/http-shared.js
Labels: [zube]: In Review

#954 fix: instrument http/https.get requests
  lib/instrumentation/http-shared.js
  lib/instrumentation/modules/http.js
  lib/instrumentation/modules/https.js
  test/instrumentation/modules/http/aborted-requests-enabled.js
  test/instrumentation/modules/http/outgoing.js
Labels: [zube]: In Review

#965 [docs] Add release notes
  docs/index.asciidoc
  docs/release-notes.asciidoc
Labels: docs
