Repository elastic/apm-agent-nodejs, pull requests merged in 2019-07, with the labels that each got.

#1179 ci(jenkins): disable builds in jenkins
  .ci/jobs/apm-agent-nodejs-downstream.yml
  .ci/jobs/apm-agent-nodejs-mbp.yml
  .ci/jobs/defaults.yml
Labels: automation, ci

#1181 ci(jenkins): move schedule to a scheduler job
  .ci/jobs/apm-agent-nodejs-schedule-daily.yml
  .ci/jobs/apm-agent-nodejs-schedule-weekly.yml
  .ci/schedule-daily.groovy
  .ci/schedule-weekly.groovy
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#1021 feat(metrics): add runtime metrics
  docs/metrics.asciidoc
  lib/metrics/platforms/generic/index.js
  lib/metrics/platforms/generic/process-cpu.js
  lib/metrics/platforms/generic/stats.js
  lib/metrics/platforms/generic/system-cpu.js
  lib/metrics/platforms/linux/index.js
  lib/metrics/platforms/linux/stats.js
  lib/metrics/registry.js
  lib/metrics/reporter.js
  lib/metrics/runtime.js
  package.json
  test/metrics/index.js
  test/test.js
Labels: [zube]: In Review, elastic-7.2, enhancement

#1185 chore: add 'npm run docker:dev' to open cwd in Docker
  .npmignore
  dev-utils/docker-compose.yml
  package.json
Labels: [zube]: In Review

#1182 ci(jenkins): ignore the branches created from the bots
  .ci/jobs/apm-agent-nodejs-downstream.yml
  .ci/jobs/apm-agent-nodejs-mbp.yml
  .ci/jobs/defaults.yml
Labels: [zube]: Inbox, automation, ci

#1189 fix(knex): abort early on unsupported version of knex
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/knex.js
Labels: [zube]: In Review

#1202 fix: use npm@6.9.0 fixed version for Node.js < 8
  .ci/docker/node-container/Dockerfile
  .ci/scripts/docker-test.sh
Labels: automation, ci

#1201 chore: clean .gitignore
  .gitignore
Labels: [zube]: In Review

#1172 ci(jenkins): add lint commit messages stage
  .ci/scripts/lint-commits.sh
  .ci/scripts/test_basic.sh
  Jenkinsfile
Labels: [zube]: In Review, automation

#1207 fix: user error step, allow empty junit results
  .ci/downstreamTests.groovy
Labels: automation, bug, ci

#1220 ci(jenkins): set Node.js repo for weekly job
  .ci/jobs/apm-agent-nodejs-schedule-weekly.yml
Labels: automation, ci

#1229 ci(jenkins): enable polling for change request/branches
  .ci/jobs/apm-agent-nodejs-mbp.yml
  .ci/jobs/defaults.yml
Labels: automation, chore, ci

#1236 ci(jenkins): exclude greenkeeper branches
  .ci/jobs/apm-agent-nodejs-mbp.yml
Labels: automation, ci

#1227 ci(jenkins): enable tests for nighlty and rc versions
  .ci/.jenkins_edge_nodejs.yml
  .ci/docker/docker-compose-edge.yml
  .ci/docker/docker-compose-node-edge-test.yml
  .ci/docker/node-edge-container/Dockerfile
  .ci/schedule-daily.groovy
  .ci/scripts/docker-test.sh
  .ci/scripts/test.sh
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#1240 ci(jenkins): remove the documentation stage
  Jenkinsfile
Labels: automation, ci

#1219 feat(metrics): breakdown graphs
  docs/metrics.asciidoc
  lib/config.js
  lib/instrumentation/span.js
  lib/instrumentation/timer.js
  lib/instrumentation/transaction.js
  lib/metrics/index.js
  lib/metrics/registry.js
  lib/metrics/reporter.js
  package.json
  test/_mock_http_client.js
  test/instrumentation/github-issue-75.js
  test/instrumentation/index.js
  test/metrics/breakdown.js
  test/sourcemaps/index.js
Labels: [zube]: In Review, elastic-7.3, enhancement

#1228 ci: smarter tav tests for pull requests
  .ci/scripts/get_tav.sh
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#1146 fix: only log deprecation warning once per function
  lib/agent.js
  lib/instrumentation/generic-span.js
Labels: [zube]: In Review

#1248 fix: a regression caused with previous commit
  Jenkinsfile
Labels: automation, bug, ci

#1247 ci(travis): cache elasticsearch deb
  .travis.yml
Labels: [zube]: In Review, ci
