Repository elastic/apm-agent-nodejs, pull requests merged in 2019-04, with the labels that each got.

#966 feat: add agent.setFramework() method
  .tav.yml
  docs/agent-api.asciidoc
  docs/index.asciidoc
  index.d.ts
  lib/agent.js
  lib/instrumentation/modules/express.js
  lib/instrumentation/modules/fastify.js
  lib/instrumentation/modules/hapi.js
  lib/instrumentation/modules/koa.js
  lib/instrumentation/modules/restify.js
  package.json
  test/agent.js
  test/config.js
  test/instrumentation/_agent.js
  test/instrumentation/modules/express/basic.js
  test/instrumentation/modules/express/set-framework.js
  test/instrumentation/modules/fastify/set-framework.js
  test/instrumentation/modules/hapi/basic.js
  test/instrumentation/modules/hapi/set-framework.js
  test/instrumentation/modules/koa/set-framework.js
  test/instrumentation/modules/restify/basic.js
  test/instrumentation/modules/restify/set-framework.js
  test/test.js
  test/types/index.ts
Labels: [zube]: In Review

#938 fix(express): transaction default name is incorrect
  lib/instrumentation/modules/express.js
  test/instrumentation/modules/express/basic.js
Labels: [zube]: In Review

#907 feat(config): add usePathAsTransactionName config option
  docs/configuration.asciidoc
  lib/config.js
  lib/instrumentation/express-utils.js
  lib/instrumentation/transaction.js
  package.json
  test/config.js
Labels: [zube]: In Review

#980 feat: sync flag on generic span
  lib/instrumentation/generic-span.js
  lib/instrumentation/index.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  test/instrumentation/span.js
  test/instrumentation/transaction.js
Labels: [zube]: In Review, enhancement

#985 fix(ts): handleUncaughtExceptions callback is optional
  index.d.ts
  test/types/index.ts
Labels: [zube]: In Review

#975 [docs] Standardize API reference
  docs/agent-api.asciidoc
  docs/index.asciidoc
  docs/span-api.asciidoc
  docs/transaction-api.asciidoc
Labels: docs

#995 fix: ensure Kubernetes/Docker container info is captured
  package.json
  test/agent.js
Labels: [zube]: In Review

#981 fix(agent): set package.json
  lib/agent.js
Labels: [zube]: In Review, bug

#967 feat(elasticsearch): expand captured requests
  .travis.yml
  lib/instrumentation/modules/elasticsearch.js
  test/instrumentation/modules/elasticsearch.js
Labels: [zube]: In Review, enhancement

#974 fix: don't add response listener to outgoing requests
  lib/instrumentation/http-shared.js
Labels: [zube]: In Review

#914 feat(template): add template shared to support jade and pug
  .tav.yml
  .travis.yml
  docs/supported-technologies.asciidoc
  lib/instrumentation/index.js
  lib/instrumentation/modules/handlebars.js
  lib/instrumentation/modules/jade.js
  lib/instrumentation/modules/pug.js
  lib/instrumentation/template-shared.js
  package.json
  test/.jenkins_tav.yml
  test/instrumentation/modules/jade.js
  test/instrumentation/modules/pug.js
Labels: [zube]: In Review

#956 Initialize config/logger before instrumentation
  lib/agent.js
Labels: [zube]: In Review

#969 feat: add traceparent getter to agent and span types
  docs/agent-api.asciidoc
  docs/span-api.asciidoc
  docs/transaction-api.asciidoc
  lib/agent.js
  lib/instrumentation/generic-span.js
  test/agent.js
  test/instrumentation/span.js
  test/instrumentation/transaction.js
Labels: [zube]: In Review, enhancement

#998 test: clean up agent test
  test/agent.js
Labels: [zube]: In Review

#1005 test(tav): don't test broken version of knex
  .tav.yml
  package.json
Labels: [zube]: In Review

#1000 docs: add info about when API's were added
  docs/agent-api.asciidoc
  docs/span-api.asciidoc
  docs/transaction-api.asciidoc
Labels: [zube]: In Review, docs

#1001 fix(ts): add TypeScript typings for new traceparent API
  index.d.ts
  lib/agent.js
  test/types/index.ts
Labels: [zube]: In Review

#1006 chore: add code comment about not changing _context
  lib/instrumentation/generic-span.js
Labels: [zube]: In Review

#1004 test(tav): restify v8+ only works on Node.js 8.6+
  .tav.yml
Labels: [zube]: In Review

#1010 feat(express-graphql): add support for version ^0.8.0
  .tav.yml
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/express-graphql.js
  package.json
Labels: [zube]: In Review

#1011 fix(package): bump elastic-apm-http-client to ^7.2.2
  package.json
Labels: [zube]: In Review

#1017 docs: improve kubernetesPodName docs
  docs/configuration.asciidoc
Labels: [zube]: In Review, docs

#1018 fix: don't create spans for APM Server requests
  lib/agent.js
Labels: [zube]: In Review

#1019 chore: rename tags to labels
  docs/agent-api.asciidoc
  docs/custom-stack.asciidoc
  docs/express.asciidoc
  docs/fastify.asciidoc
  docs/hapi.asciidoc
  docs/koa.asciidoc
  docs/lambda.asciidoc
  docs/redirects.asciidoc
  docs/restify.asciidoc
  docs/span-api.asciidoc
  docs/transaction-api.asciidoc
  index.d.ts
  lib/agent.js
  lib/instrumentation/generic-span.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  test/agent.js
  test/instrumentation/span.js
  test/instrumentation/transaction.js
  test/integration/api-schema/basic.js
  test/types/index.ts
Labels: [zube]: In Review, elastic-7.1, enhancement

#1026 ci: fast-close apm-server mock
  test/_apm_server.js
Labels: [zube]: In Review, ci

#1027 feat(config): more flexible key/value pairs
  lib/config.js
  package.json
  test/config.js
Labels: [zube]: In Review, enhancement

#1020 feat(config): support global labels
  docs/configuration.asciidoc
  lib/config.js
  package.json
  test/_apm_server.js
  test/config.js
Labels: [zube]: In Review, elastic-7.1, enhancement

#1029 ci: add Node.js 12 to CI
  .travis.yml
  test/.jenkins_nodejs.yml
  test/.jenkins_tav_nodejs.yml
Labels: [zube]: In Review, ci

#1030 docs: add tip/warning to labels
  docs/agent-api.asciidoc
Labels: docs

#1033 added doc example for globalLabels env var
  docs/configuration.asciidoc
Labels: [zube]: In Review, docs

#1037 chore(tav): update tedious support ranges
  .tav.yml
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review, chore, ci

#1039 docs: fix location of custom context
  docs/agent-api.asciidoc
Labels: docs
