Repository elastic/apm-agent-nodejs, pull requests merged in 2019-10, with the labels that each got.

#1419 fix(package): update elastic-apm-http-client to version 9.0.0
  package.json
Labels: [zube]: In Review

#1425 ci(jenkins): reuse top level agent
  .ci/downstreamTests.groovy
  .ci/linting.groovy
  Jenkinsfile
Labels: automation, ci

#1423 feat(mongodb): instrumentation
  .tav.yml
  docs/supported-technologies.asciidoc
  lib/instrumentation/index.js
  lib/instrumentation/modules/mongodb.js
  package.json
  test/_mock_http_client_states.js
  test/instrumentation/modules/mongodb.js
Labels: [zube]: In Review, enhancement

#1429 fix: write stack trace of uncaught exceptions to STDERR
  docs/configuration.asciidoc
  lib/agent.js
  lib/config.js
  test/config.js
  test/test.js
  test/uncaught-exceptions/log-uncaught-exceptions-off.js
  test/uncaught-exceptions/log-uncaught-exceptions-on.js
Labels: [zube]: In Review

#1434 perf: cache 'ids' value of transactions and spans
  lib/instrumentation/generic-span.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
Labels: [zube]: In Review

#1432 fix: change logUncaughtExceptions default to false
  docs/configuration.asciidoc
  lib/config.js
  test/config.js
  test/uncaught-exceptions/log-uncaught-exceptions-off.js
  test/uncaught-exceptions/log-uncaught-exceptions-on.js
Labels: [zube]: In Review

#1438 [2.x] perf: cache 'ids' value of transactions and spans (#1434)
  lib/instrumentation/generic-span.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
Labels: backport

#1428 [docs] Documentation restructure
  docs/agent-api.asciidoc
  docs/configuration.asciidoc
  docs/custom-spans.asciidoc
  docs/custom-stack.asciidoc
  docs/custom-transactions.asciidoc
  docs/express.asciidoc
  docs/fastify.asciidoc
  docs/hapi.asciidoc
  docs/index.asciidoc
  docs/intro.asciidoc
  docs/koa.asciidoc
  docs/lambda.asciidoc
  docs/log-correlation.asciidoc
  docs/opentracing.asciidoc
  docs/redirects.asciidoc
  docs/restify.asciidoc
  docs/set-up.asciidoc
  docs/setup.asciidoc
  docs/shared-set-up.asciidoc
  docs/source-maps.asciidoc
  docs/supported-technologies.asciidoc
Labels: docs

#1439 fix: always end transaction when socket is closed prematurely
  lib/instrumentation/http-shared.js
  test/instrumentation/modules/http/aborted-requests-enabled.js
Labels: [zube]: In Review, backport:2.x

#1443 [2.x] docs: documentation restructure (#1428)
  docs/agent-api.asciidoc
  docs/configuration.asciidoc
  docs/custom-spans.asciidoc
  docs/custom-stack.asciidoc
  docs/custom-transactions.asciidoc
  docs/express.asciidoc
  docs/fastify.asciidoc
  docs/hapi.asciidoc
  docs/index.asciidoc
  docs/intro.asciidoc
  docs/koa.asciidoc
  docs/lambda.asciidoc
  docs/log-correlation.asciidoc
  docs/opentracing.asciidoc
  docs/redirects.asciidoc
  docs/restify.asciidoc
  docs/set-up.asciidoc
  docs/setup.asciidoc
  docs/shared-set-up.asciidoc
  docs/source-maps.asciidoc
  docs/supported-technologies.asciidoc
Labels: docs

#1451 ci(jenkins): fix wrong label
  Jenkinsfile
Labels: automation, ci

#1445 [2.x] fix: always end transaction when socket is closed prematurely (#1439)
  lib/instrumentation/http-shared.js
  test/instrumentation/modules/http/aborted-requests-enabled.js
Labels: backport

#1471 ci(jenkins): move Jenkinsfile inside .ci folder
  .ci/Jenkinsfile
  .ci/jobs/apm-agent-nodejs-mbp.yml
  .npmignore
Labels: automation, ci

#1473 fix(tedious): support 6.5+
  lib/instrumentation/modules/tedious.js
Labels: [zube]: In Review, bug

#1464 ci: add new Node.js versions to CI
  .appveyor.yml
  .ci/.jenkins_nightly_nodejs.yml
  .ci/.jenkins_nodejs.yml
  .ci/.jenkins_rc_nodejs.yml
  .ci/.jenkins_tav_nodejs.yml
  .travis.yml
  test/instrumentation/modules/tedious.js
Labels: [zube]: In Review, backport:2.x

#1476 refactor: use smarter shimming of graphql module
  lib/instrumentation/modules/graphql.js
  package.json
Labels: [zube]: In Review, backport:2.x

#1466 fix(metrics): do not send transaction breakdowns when disabled
  lib/instrumentation/transaction.js
  test/metrics/breakdown.js
Labels: [zube]: In Review, bug

#1477 fix(tedious): ensure shimmed module exposes same API
  lib/instrumentation/modules/tedious.js
Labels: [zube]: In Progress, backport:2.x

#1484 ci(memcached): ensure host env var is available in edge tests
  .ci/docker/docker-compose-node-edge-test.yml
Labels: [zube]: In Review, bug, ci

#1485 chore(knex): bump knex dependency and fix tests
  .tav.yml
  docs/supported-technologies.asciidoc
  package.json
  test/instrumentation/modules/pg/knex.js
Labels: [zube]: In Review, chore, test

#1487 chore(mysql2): bump mysql2 dependency
  .tav.yml
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/mysql2.js
  package.json
Labels: [zube]: In Review, enhancement

#1463 feat(http,http2): add http context info
  lib/instrumentation/http-shared.js
  lib/instrumentation/modules/http2.js
  lib/instrumentation/span.js
  package.json
  test/instrumentation/modules/http/outgoing.js
  test/instrumentation/modules/http2.js
  test/instrumentation/span.js
Labels: [zube]: In Review, enhancement

#1488 [2.x] fix(tedious): support 6.5+ (#1473)
  lib/instrumentation/modules/tedious.js
Labels: backport

#1489 [2.x] fix(metrics): do not send transaction breakdowns when disabled (#1466)
  lib/instrumentation/transaction.js
  test/metrics/breakdown.js
Labels: backport

#1491 [2.x] ci(memcached): ensure host env var is available in edge tests (#1484)
  .ci/docker/docker-compose-node-edge-test.yml
Labels: backport

#1492 [2.x] chore(mysql2): bump mysql2 dependency (#1487)
  .tav.yml
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/mysql2.js
  package.json
Labels: backport

#1490 [2.x] refactor: use smarter shimming of graphql module (#1476)
  lib/instrumentation/modules/graphql.js
  package.json
Labels: backport

#1496 [2.x] fix(tedious): ensure shimmed module exposes same API (#1477)
  lib/instrumentation/modules/tedious.js
Labels: backport

#1478 [2.x] ci(jenkins): move Jenkinsfile inside .ci folder (#1471)
  .ci/Jenkinsfile
  .ci/jobs/apm-agent-nodejs-mbp.yml
  .npmignore
Labels: automation, backport, ci
