Repository elastic/apm-agent-nodejs, pull requests merged in 2019-06, with the labels that each got.

#1043 [ci] add files for JJBB jobs
  .ci/bin/check_paths_for_matches.py
  .ci/jobs/apm-agent-nodejs-mbp.yml
  .ci/jobs/apm-agent-nodejs.yml
  .ci/jobs/defaults.yml
Labels: [zube]: In Review

#1108 test: add knex v0.17.x to TAV test matrix
  .tav.yml
  package.json
Labels: [zube]: In Review

#1112 test(tav): add set-framework tests to tav test matrix
  .tav.yml
Labels: [zube]: In Review

#1113 ci(jenkins): don't pollute package.json with tap-junit
  test/script/run_tests.sh
Labels: [zube]: In Review

#1116 ci(jenkins): new notifications and reports to Elasticsearch
  Jenkinsfile
Labels: [zube]: In Review

#1118 ci(travis): add Node.js v12 nightly (no async hooks) build
  .travis.yml
Labels: [zube]: In Review

#1111 fix(express): don't swallow error handling middleware
  .tav.yml
  lib/instrumentation/modules/express.js
  test/instrumentation/modules/express/capture-exceptions-off.js
  test/instrumentation/modules/express/capture-exceptions-on.js
Labels: [zube]: In Review

#1122 chore: add .ci folder to .npmignore
  .npmignore
Labels: [zube]: In Review

#1127 test: fix broken intake API schema tests
  test/integration/api-schema/download-json-schemas.sh
Labels: [zube]: In Review

#1130 chore(config): sort configs alphabetically
  index.d.ts
  lib/config.js
Labels: [zube]: In Review, enhancement, technical debt

#1025 ci(jenkins): add tav tests
  .ci/.editorconfig
  .ci/.jenkins_nodejs.yml
  .ci/.jenkins_tav.yml
  .ci/.jenkins_tav_nodejs.yml
  .ci/docker/docker-compose-all.yml
  .ci/docker/docker-compose-cassandra.yml
  .ci/docker/docker-compose-elasticsearch.yml
  .ci/docker/docker-compose-mongodb.yml
  .ci/docker/docker-compose-mssql.yml
  .ci/docker/docker-compose-mysql.yml
  .ci/docker/docker-compose-node-test.yml
  .ci/docker/docker-compose-postgres.yml
  .ci/docker/docker-compose-redis.yml
  .ci/docker/docker-compose.yml
  .ci/docker/node-container/Dockerfile
  .ci/downstreamTests.groovy
  .ci/scripts/convert_tap_to_junit.sh
  .ci/scripts/docker-test.sh
  .ci/scripts/lint-commits.sh
  .ci/scripts/test.sh
  .ci/scripts/test_basic.sh
  Jenkinsfile
  test/.jenkins_tav.yml
Labels: [zube]: In Progress

#1132 ci: github checks for the pull requests
  Jenkinsfile
Labels: automation

#1138 fix(package): bump semver to ^6.1.1
  package.json
Labels: [zube]: In Review

#1139 chore(package): bump all devDependencies
  package.json
Labels: [zube]: In Review

#1106 feat(config): add environment option
  docs/configuration.asciidoc
  index.d.ts
  lib/config.js
  lib/metrics/index.js
  lib/metrics/registry.js
  package.json
  test/config.js
Labels: [zube]: In Review, elastic-7.2, enhancement

#1159 ci(jenkins): run integrations tests for the nodejs agent only
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#1170 ci(jenkins): enable pull requests using the upstream repo
  Jenkinsfile
Labels: [zube]: Inbox, automation, ci

#1171 ci: notify on cleanup stage
  Jenkinsfile
Labels: [zube]: In Review, automation

#1175 ci(jenkins): notify first time contributor github check
  Jenkinsfile
Labels: automation, ci
