Repository elastic/apm-agent-nodejs, pull requests merged in 2019-05, with the labels that each got.

#1036 chore(package): update restify to version 8.3.1
  package.json
  test/config.js
  test/instrumentation/modules/restify/basic.js
  test/instrumentation/modules/restify/set-framework.js
Labels: [zube]: In Review, chore

#1041 fix(config): do not use ELASTIC_APM_ prefix for k8s
  docs/configuration.asciidoc
  lib/config.js
  test/config.js
Labels: [zube]: In Review, enhancement

#1044 fix(instrumentation): prevent handler leak in bindEmitter
  lib/instrumentation/index.js
  test/instrumentation/index.js
Labels: [zube]: In Review, bug

#1045 ci: disable metrics collector when not being tested
  test/config.js
  test/instrumentation/modules/apollo-server-express.js
  test/instrumentation/modules/bluebird/bluebird.js
  test/instrumentation/modules/bluebird/cancel.js
  test/instrumentation/modules/cassandra-driver/index.js
  test/instrumentation/modules/elasticsearch.js
  test/instrumentation/modules/express-graphql.js
  test/instrumentation/modules/express-queue.js
  test/instrumentation/modules/express/basic.js
  test/instrumentation/modules/fastify/async-await.js
  test/instrumentation/modules/fastify/fastify.js
  test/instrumentation/modules/finalhandler.js
  test/instrumentation/modules/generic-pool.js
  test/instrumentation/modules/graphql.js
  test/instrumentation/modules/handlebars.js
  test/instrumentation/modules/hapi/basic.js
  test/instrumentation/modules/http/github-179.js
  test/instrumentation/modules/http2.js
  test/instrumentation/modules/ioredis.js
  test/instrumentation/modules/jade.js
  test/instrumentation/modules/koa-router/index.js
  test/instrumentation/modules/mimic-response.js
  test/instrumentation/modules/mongodb-core.js
  test/instrumentation/modules/mysql/mysql.js
  test/instrumentation/modules/mysql/pool-release-1.js
  test/instrumentation/modules/mysql2/mysql.js
  test/instrumentation/modules/mysql2/pool-release-1.js
  test/instrumentation/modules/pg/knex.js
  test/instrumentation/modules/pg/pg.js
  test/instrumentation/modules/pug.js
  test/instrumentation/modules/redis.js
  test/instrumentation/modules/restify/basic.js
  test/instrumentation/modules/tedious.js
  test/instrumentation/modules/ws.js
Labels: [zube]: In Review, chore, ci

#1050 [APM-CI][All] Make the trigger by comment case-insensitive
  Jenkinsfile
Labels: automation

#1057 chore: add Node.js 12 to package.json engines field
  package.json
Labels: [zube]: In Review

#1062 chore: add missing TODO
  lib/config.js
Labels: [zube]: In Review

#1049 docs: document additional capture error options
  docs/agent-api.asciidoc
  docs/index.asciidoc
Labels: [zube]: In Review

#1061 ci(travis): add Node.js 12 pre-release tests
  .travis.yml
Labels: [zube]: In Review

#1059 fix(instrumentation): explicitly use `require`
  lib/instrumentation/index.js
Labels: [zube]: In Review

#1058 chore(package): update ws to version 7.0.0
  .tav.yml
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/ws.js
  package.json
  test/config.js
  test/instrumentation/modules/ws.js
Labels: [zube]: In Review

#1070 fix(express-slash): expose express handle properties
  lib/instrumentation/modules/express.js
  test/instrumentation/modules/express/basic.js
Labels: [zube]: In Review

#1074 fix: url.parse expects req.url not req
  lib/instrumentation/express-utils.js
Labels: [zube]: In Review, bug

#1081 fix(span): use correct logger location
  lib/instrumentation/generic-span.js
Labels: [zube]: In Review, bug

#1086 test(fastify): exclude v2.4.0 from test matrix
  .tav.yml
Labels: [zube]: In Review

#1080 test: verify internal http requests are ignored
  test/integration/skip-internal-http-spans.js
Labels: [zube]: In Review, test

#1083 test(travis): split TAV builds into 5 groups per Node.js version
  .travis.yml
Labels: [zube]: In Review, ci

#1084 test(jenkins): fail test if part of pipeline fails
  test/script/run_tests.sh
Labels: [zube]: In Review

#1091 chore(package): update tape to version 4.10.2
  package.json
Labels: [zube]: In Review

#1089 fix: don't add traceparent header to signed AWS requests
  lib/instrumentation/http-shared.js
  package.json
  test/instrumentation/modules/http/aws.js
Labels: [zube]: In Review

#1013 fix(express): improve names for routes added via app.use()
  lib/instrumentation/express-utils.js
  test/instrumentation/modules/express-graphql.js
  test/instrumentation/modules/express/basic.js
  test/instrumentation/modules/graphql.js
Labels: [zube]: In Review

#1092 fix(metrics): report correct CPU usage on Linux
  lib/metrics/platforms/linux/index.js
  lib/metrics/platforms/linux/stats.js
  lib/metrics/registry.js
Labels: [zube]: In Review
