Repository elastic/apm-agent-nodejs, pull requests merged in 2019-02, with the labels that each got.

#834 test(mock): add sendMetricSet to http client mock
  test/_mock_http_client.js
Labels: [zube]: In Review, ci

#838 test(apollo-server-express): exclude range broken by core-js
  .tav.yml
Labels: [zube]: In Review, ci

#837 fix(metrics): ensure NaN becomes 0, not null
  lib/metrics/platforms/linux/stats.js
Labels: [zube]: In Review, bug

#840 ci(transaction): increase acceptable duration range
  test/instrumentation/transaction.js
Labels: [zube]: In Review, ci

#841 ci: fix agent mock metricsInterval
  test/instrumentation/_agent.js
Labels: [zube]: In Review, ci

#844 test(schema): metadata service is now optional
  test/integration/api-schema/basic.js
Labels: [zube]: In Review, ci

#801 [APM-CI] Jenkins Pipeline for Agent Node.js
  Jenkinsfile
  test/docker-compose.ci.yml
  test/docker-compose.yml
  test/instrumentation/transaction.js
  test/script/docker/cleanup.sh
  test/script/docker/run_tests.sh
  test/script/run_tests.sh
Labels: automation

#842 fix(express): ensure correct transaction names
  lib/instrumentation/express-utils.js
  lib/instrumentation/modules/express.js
  lib/instrumentation/modules/graphql.js
  test/instrumentation/modules/express.js
Labels: [zube]: In Progress, bug

#849 ci: pin tape as 4.10 breaks test suite
  package.json
Labels: [zube]: In Review, ci

#848 fix(config): apiRequestSize should be 768kb
  docs/configuration.asciidoc
  lib/config.js
  test/config.js
Labels: [zube]: In Review, bug

#833 refactor: extract trace-context
  lib/instrumentation/generic-span.js
  lib/instrumentation/trace-context.js
  package.json
  test/instrumentation/modules/http/basic.js
  test/instrumentation/modules/http/outgoing.js
  test/instrumentation/trace-context.js
Labels: [zube]: In Review, enhancement

#862 [docs] Fix metrics docs formatting
  docs/metrics.asciidoc
Labels: docs

#861 [APM-CI] some exceptions are not convert to String when you call error step error step
  Jenkinsfile
Labels: automation

#871 feat(lambda): support promise form
  lib/agent.js
  lib/lambda.js
  package.json
  test/agent.js
  test/lambda/_util.js
  test/lambda/callbacks.js
  test/lambda/context.js
  test/lambda/mock/agent.js
  test/lambda/mock/transaction.js
  test/lambda/promises.js
  test/test.js
Labels: [zube]: In Review, enhancement

#875 ci(jenkins): Bump shared lib version to 1.0.7
  Jenkinsfile
Labels: [zube]: In Progress, automation

#872 fix(metrics): prevent 0ms timers from being created
  lib/metrics/registry.js
Labels: [zube]: In Review, bug, ci

#829 feat: extract filters
  lib/agent.js
  lib/filters/http-headers.js
  lib/filters/index.js
  package.json
  test/_agent.js
  test/filters.js
  test/instrumentation/_agent.js
Labels: [zube]: In Review, enhancement

#885 chore(package): bump hapi dev dependency to ^18.1.0
  .tav.yml
  docs/supported-technologies.asciidoc
  package.json
Labels: [zube]: In Review
