Repository elastic/apm-agent-nodejs, pull requests merged in 2019-08, with the labels that each got.

#1231 ci(jenkins): add tests with elastic_apm_async_hooks=false
  .ci/docker/docker-compose-node-test.yml
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#1251 chore: pin wait-on to 3.2.0
  package.json
Labels: [zube]: In Review

#1252 ci(travis): disable npm cache
  .travis.yml
Labels: [zube]: In Review

#1258 [docs] Add information for explicitly calling `apm.start()`
  docs/setup.asciidoc
Labels: docs

#1246 chore: make hapi instrumentation support @hapi/hapi rename
  .tav.yml
  .travis.yml
  docs/agent-api.asciidoc
  docs/index.asciidoc
  docs/supported-technologies.asciidoc
  lib/instrumentation/index.js
  package.json
  test/config.js
  test/instrumentation/modules/hapi/basic-legacy-path.js
  test/instrumentation/modules/hapi/basic.js
  test/instrumentation/modules/hapi/set-framework-2.js
  test/instrumentation/modules/hapi/shared.js
Labels: [zube]: In Review

#1260 ci(jenkins): lint commits in the test parallel stage
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#1267 ci(jenkins): more debug output for smartTAV
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#1263 ci(appveyor): upgrade Node.js version from 8 to 10
  .appveyor.yml
Labels: [zube]: In Review, ci

#1262 feat: allow agent.clearPatches to be called with array of names
  .tav.yml
  docs/agent-api.asciidoc
  index.d.ts
  lib/agent.js
  lib/instrumentation/index.js
  test/types/index.ts
Labels: [zube]: In Review

#1269 docs: fix invalid link to elasticsearch npm package
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review, docs

#1274 fix: be less chatty if span stack traces cannot be parsed
  lib/instrumentation/span.js
Labels: [zube]: In Review

#1275 perf: use for-of instead of forEach
  lib/agent.js
  lib/config.js
  lib/instrumentation/generic-span.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/express-graphql.js
  lib/instrumentation/modules/express.js
  lib/instrumentation/modules/graphql.js
  lib/instrumentation/patch-async.js
  lib/instrumentation/shimmer.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  lib/metrics/platforms/generic/index.js
  lib/metrics/platforms/linux/index.js
  lib/metrics/platforms/linux/stats.js
  lib/metrics/reporter.js
  lib/metrics/runtime.js
  lib/parsers.js
  test/integration/skip-internal-http-spans.js
Labels: [zube]: In Review

#1268 ci(jenkins): support for @path/module in smart tav
  .ci/scripts/get_tav.sh
Labels: [zube]: In Review, automation, ci

#1281 ci(jenkins): async hook false runs in parallel
  Jenkinsfile
Labels: automation, ci, enhancement

#1277 ci(jenkins): run tests without async hooks on Node.js nightly
  .ci/.jenkins_nightly_nodejs.yml
  .ci/.jenkins_rc_nodejs.yml
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#1273 feat(metrics): add metricsLimit option
  docs/configuration.asciidoc
  lib/config.js
  lib/metrics/registry.js
  lib/metrics/reporter.js
  package.json
  test/config.js
  test/metrics/index.js
Labels: [zube]: In Review, enhancement

#1255 feat(express-graphql): add support for v0.9
  .tav.yml
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/express-graphql.js
  package.json
  test/config.js
  test/instrumentation/modules/express-graphql.js
Labels: [zube]: In Review

#1284 chore: prepare code style for new version of linter
  lib/agent.js
  lib/config.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/modules/elasticsearch.js
  lib/instrumentation/modules/http2.js
  lib/instrumentation/transaction.js
  lib/metrics/platforms/linux/stats.js
  lib/metrics/reporter.js
  test/config.js
  test/instrumentation/modules/http/aws.js
  test/instrumentation/modules/mongodb-core.js
  test/instrumentation/transaction.js
  test/metrics/breakdown.js
  test/metrics/index.js
  test/parsers.js
  test/script/cli.js
  test/test.js
Labels: [zube]: In Review

#1283 ci(jenkins): run edge tests in parallel
  Jenkinsfile
Labels: [zube]: In Progress

#1299 fix(package): bump stackman to ^4.0.0
  package.json
Labels: [zube]: In Review

#1300 fix: change agent active status log message to debug level
  lib/agent.js
  test/config.js
Labels: [zube]: In Review

#1297 ci(jenkins): avoid builds in the master worker
  .ci/downstreamTests.groovy
  Jenkinsfile
Labels: automation, ci

#1302 docs: remove extra line-break in code example
  docs/setup.asciidoc
Labels: [zube]: In Review, docs

#1144 feat(instrumentation): add memcached
  .ci/.jenkins_tav.yml
  .ci/docker/docker-compose-all.yml
  .ci/docker/docker-compose-memcached.yml
  .ci/docker/docker-compose-node-test.yml
  .ci/docker/docker-compose.yml
  .ci/scripts/test.sh
  .tav.yml
  .travis.yml
  docs/supported-technologies.asciidoc
  lib/instrumentation/index.js
  lib/instrumentation/modules/memcached.js
  package.json
  test/docker-compose.ci.yml
  test/docker-compose.yml
  test/instrumentation/modules/memcached.js
  test/script/local-deps-start.sh
  test/script/local-deps-stop.sh
Labels: [zube]: In Review

#1306 fix(async_hooks): properly update sync flag
  lib/instrumentation/async-hooks.js
  test/instrumentation/async-hooks.js
Labels: [zube]: In Review, bug

#1303 feat: add configFile config option
  docs/configuration.asciidoc
  docs/setup.asciidoc
  lib/config.js
Labels: [zube]: In Review

#1279 ci: add Node.js v13 nightly to test matrix
  .ci/.jenkins_nightly_nodejs.yml
  .ci/.jenkins_rc_nodejs.yml
  .travis.yml
  Jenkinsfile
Labels: [zube]: In Review

#1304 ci(jenkins): avoid using the any to skip the master
  .ci/downstreamTests.groovy
  Jenkinsfile
Labels: automation, ci, enhancement

#1307 chore(package): bump dependency-check to ^4.1.0
  package.json
Labels: [zube]: In Review

#1308 ci(travis): don't run TAV, Nightly, or RC builds on Travis
  .travis.yml
Labels: [zube]: In Review, ci

#1311 docs: document serviceName character limitations
  docs/configuration.asciidoc
Labels: [zube]: In Review, docs

#1314 Revert "ci(jenkins): avoid using the any to skip the master (#1304)"
  .ci/downstreamTests.groovy
  Jenkinsfile
Labels: automation, ci

#1278 fix: avoid throwing when agent is in active: false mode
  lib/instrumentation/transaction.js
  lib/metrics/index.js
  test/agent.js
  test/metrics/index.js
Labels: [zube]: In Review, enhancement
