Repository elastic/apm-agent-nodejs, pull requests merged in 2019-12, with the labels that each got.

#1554 ci(jenkins): cancel previous running builds
  .ci/Jenkinsfile
Labels: automation, ci

#1558 ci(jenkins): support isGitRegionMatch
  .ci/Jenkinsfile
Labels: automation, bug, ci

#1553 ci(jenkins): trigger opbeans release process
  .ci/Jenkinsfile
Labels: automation

#1570 ci(jenkins): fix linting in branches and tidyup
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
  .ci/linting.groovy
Labels: automation, bug, ci

#1572 [docs] update doc build script
  docs/scripts/build_docs.sh
Labels: docs
