Repository elastic/apm-agent-nodejs, pull requests merged in 2019-09, with the labels that each got.

#1324 fix(package): bump elastic-apm-http-client to version ^8.2.1
  package.json
Labels: [zube]: In Review

#1323 chore: improve GitHub issue template
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: [zube]: In Review

#1326 ci(jenkins): Set GitHub notification context to apm-ci
  .ci/jobs/apm-agent-nodejs-downstream.yml
  .ci/jobs/apm-agent-nodejs-mbp.yml
Labels: automation, ci

#1328 ci(travis): don't send status e-mails
  .travis.yml
Labels: [zube]: In Review

#1325 ci(jenkins): decouple linting from CI pipeline
  .ci/jobs/apm-agent-nodejs-linting-mbp.yml
  .ci/linting.groovy
  .ci/scripts/lint-commits.sh
  .ci/scripts/test_basic.sh
  .ci/scripts/test_types_babel_esm.sh
  Jenkinsfile
Labels: [zube]: In Review, automation, ci, enhancement

#1331 ci(jenkins): run all the stages
  .ci/schedule-daily.groovy
Labels: automation, ci, enhancement

#1333 test: improve test output
  test/instrumentation/modules/http/_assert.js
  test/instrumentation/modules/http/aborted-requests-enabled.js
Labels: [zube]: In Progress

#1339 fix(http): response context propagation on Node.js 12.0 - 12.2
  lib/instrumentation/http-shared.js
Labels: [zube]: In Review, bug

#1145 Add benchmarks
  .ci/schedule-daily.groovy
  .ci/scripts/prepare-benchmarks-env.sh
  .ci/scripts/run-benchmarks.sh
  .gitignore
  Jenkinsfile
  TESTING.md
  package.json
  test/benchmarks/001-transaction-and-span-no-stack-trace.js
  test/benchmarks/002-transaction-and-span-overhead-realistic-size.js
  test/benchmarks/003-transaction-and-span-with-stack-trace.js
  test/benchmarks/004-transaction.js
  test/benchmarks/005-transaction-reading-file.js
  test/benchmarks/scripts/run-benchmarks-ci.sh
  test/benchmarks/scripts/run-benchmarks.sh
  test/benchmarks/utils/analyzer.js
  test/benchmarks/utils/apm-server.js
  test/benchmarks/utils/bench.js
  test/benchmarks/utils/callstack.js
  test/benchmarks/utils/result-logger.js
Labels: [zube]: In Review

#1345 chore: fix patch method argument names
  lib/instrumentation/index.js
Labels: [zube]: In Review

#1346 feat: add support for @koa/router
  .ci/.jenkins_tav.yml
  .tav.yml
  docs/supported-technologies.asciidoc
  lib/instrumentation/index.js
  lib/instrumentation/modules/koa-router.js
  package.json
  test/instrumentation/modules/koa-router/index.js
  test/instrumentation/modules/koa-router/new-name.js
  test/instrumentation/modules/koa-router/old-name.js
  test/instrumentation/modules/koa-router/shared.js
Labels: [zube]: In Review

#1344 ci(jenkins): add @hapi/hapi to TAV test matrix
  .ci/.jenkins_tav.yml
Labels: [zube]: In Review, automation, ci

#1351 ci(jenkins): tav with different formats
  Jenkinsfile
Labels: automation, bug, ci

#1352 ci(jenkins): don't run TAV tests for Node.js core modules
  .ci/scripts/get_tav.sh
Labels: [zube]: In Review

#1357 fix: improve debug output when detecting incoming http request
  lib/instrumentation/http-shared.js
Labels: [zube]: In Review

#1342 test(mongodb-core): fix tav tests
  test/instrumentation/modules/mongodb-core.js
Labels: [zube]: In Review, test

#1359 test: add captureError tests for request/response options
  test/agent.js
Labels: [zube]: In Review, test

#1358 docs: improve AWS Lambda docs
  docs/agent-api.asciidoc
Labels: [zube]: In Review, docs

#1356 fix(package): bump all dependencies
  package.json
Labels: [zube]: In Review

#1335 feat: add toString methods for logging
  docs/agent-api.asciidoc
  docs/span-api.asciidoc
  docs/transaction-api.asciidoc
  lib/agent.js
  lib/instrumentation/ids.js
  lib/instrumentation/index.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  test/agent.js
  test/instrumentation/span.js
  test/instrumentation/transaction.js
Labels: [zube]: In Review, enhancement

#1363 ci(jenkins): create the yaml header
  .ci/scripts/get_tav.sh
  lib/instrumentation/modules/http.js
Labels: automation, bug, ci

#1365 test: allow mock APM Server to be initiated without args
  test/_apm_server.js
Labels: [zube]: In Review, test

#1366 test: don't swallow promise rejections during test
  test/_apm_server.js
  test/_promise_rejection.js
  test/instrumentation/modules/bluebird/bluebird.js
  test/test.js
Labels: [zube]: In Review

#1355 chore(package): bump 'standard' linter to ^14.3.1
  lib/agent.js
  lib/instrumentation/modules/express.js
  lib/parsers.js
  package.json
  test/agent.js
  test/benchmarks/utils/result-logger.js
  test/central-config-enabled.js
  test/instrumentation/modules/express-graphql.js
  test/instrumentation/modules/graphql.js
Labels: [zube]: In Review

#1245 refactor(graphql): use custom transaction type for graphql requests
  lib/instrumentation/modules/graphql.js
  test/instrumentation/modules/apollo-server-express.js
  test/instrumentation/modules/express-graphql.js
Labels: [zube]: In Review, breaking change, enhancement

#1291 feat: use external as span type
  lib/instrumentation/http-shared.js
  lib/instrumentation/modules/http2.js
  test/instrumentation/modules/elasticsearch.js
  test/instrumentation/modules/http2.js
Labels: [zube]: In Review, breaking change, enhancement

#1298 feat(http): add monitorIncomingHTTPRequests config
  docs/configuration.asciidoc
  index.d.ts
  lib/config.js
  lib/instrumentation/modules/http.js
  lib/instrumentation/modules/http2.js
  lib/instrumentation/modules/https.js
  test/config.js
  test/instrumentation/_agent.js
  test/instrumentation/index.js
  test/instrumentation/modules/http/disabling.js
Labels: [zube]: In Review, breaking change, enhancement

#1367 test: fix http disabling test
  test/instrumentation/modules/http/disabling.js
Labels: [zube]: In Review

#1292 feat: split types
  docs/agent-api.asciidoc
  docs/span-api.asciidoc
  docs/transaction-api.asciidoc
  index.d.ts
  lib/agent.js
  lib/instrumentation/generic-span.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/cassandra-driver.js
  lib/instrumentation/modules/elasticsearch.js
  lib/instrumentation/modules/graphql.js
  lib/instrumentation/modules/http2.js
  lib/instrumentation/modules/ioredis.js
  lib/instrumentation/modules/mongodb-core.js
  lib/instrumentation/modules/mysql.js
  lib/instrumentation/modules/mysql2.js
  lib/instrumentation/modules/pg.js
  lib/instrumentation/modules/redis.js
  lib/instrumentation/modules/tedious.js
  lib/instrumentation/modules/ws.js
  lib/instrumentation/span.js
  lib/instrumentation/template-shared.js
  lib/instrumentation/transaction.js
  test/agent.js
  test/config.js
  test/instrumentation/index.js
  test/instrumentation/modules/apollo-server-express.js
  test/instrumentation/modules/cassandra-driver/index.js
  test/instrumentation/modules/elasticsearch.js
  test/instrumentation/modules/express-graphql.js
  test/instrumentation/modules/graphql.js
  test/instrumentation/modules/handlebars.js
  test/instrumentation/modules/http/disabling.js
  test/instrumentation/modules/http2.js
  test/instrumentation/modules/ioredis.js
  test/instrumentation/modules/jade.js
  test/instrumentation/modules/mongodb-core.js
  test/instrumentation/modules/mysql/mysql.js
  test/instrumentation/modules/mysql2/mysql.js
  test/instrumentation/modules/pg/knex.js
  test/instrumentation/modules/pg/pg.js
  test/instrumentation/modules/pug.js
  test/instrumentation/modules/redis.js
  test/instrumentation/modules/tedious.js
  test/instrumentation/modules/ws.js
  test/instrumentation/span.js
  test/instrumentation/transaction.js
  test/metrics/breakdown.js
  test/types/index.ts
Labels: [zube]: In Review, breaking change, enhancement

#1373 test: ensure proper cleanup between config tests
  lib/instrumentation/async-hooks.js
  test/_agent.js
  test/config.js
Labels: [zube]: In Review

#1376 fix(parsers): ensure non-string bodies are converted
  lib/parsers.js
  test/parsers.js
Labels: [zube]: In Review, backport:2.x, bug

#1377 chore: update backport tooling and docs
  .backportrc.json
  CONTRIBUTING.md
  package.json
Labels: [zube]: In Review

#1114 feat: allow manual instrumentation when instrument is set to false
  docs/configuration.asciidoc
  lib/instrumentation/index.js
  test/_mock_http_client.js
  test/config.js
Labels: [zube]: In Review, breaking change, enhancement

#1375 docs: set upper bounds for current mongo support
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review, docs

#1382 [2.x] docs: set upper bounds for current mongo support (#1375)
  docs/supported-technologies.asciidoc
Labels: backport

#1380 [2.x] test: ensure proper cleanup between config tests (#1373)
  lib/instrumentation/async-hooks.js
  test/_agent.js
  test/config.js
Labels: backport

#1381 [2.x] fix: capture all non-string http bodies (#1376)
  lib/parsers.js
  test/parsers.js
Labels: backport

#1387 ci: run esm tests on all 9+ Node.js versions
  .ci/scripts/test_types_babel_esm.sh
  package.json
  test/esm/index.mjs
  test/script/run_tests.sh
Labels: [zube]: In Review, backport:2.x

#1391 ci(jenkins): 2.x branch on a daily basis
  .ci/schedule-daily.groovy
Labels: automation, ci

#1390 [2.x] ci: run esm tests on all 9+ Node.js versions (#1387)
  .ci/scripts/test_types_babel_esm.sh
  package.json
  test/esm/index.mjs
  test/script/run_tests.sh
Labels: backport

#1389 fix: support all falsy return values from error filters
  lib/agent.js
  test/agent.js
Labels: [zube]: In Review, backport:2.x

#1383 chore: drop support for older Node.js versions
  .ci/.jenkins_nodejs.yml
  .ci/.jenkins_tav_nodejs.yml
  .ci/docker/node-container/Dockerfile
  .ci/docker/node-edge-container/Dockerfile
  .ci/scripts/docker-test.sh
  .ci/scripts/test_types_babel_esm.sh
  .travis.yml
  Jenkinsfile
  docs/supported-technologies.asciidoc
  lib/config.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/http.js
  lib/instrumentation/transaction.js
  lib/lambda.js
  lib/metrics/platforms/generic/index.js
  lib/metrics/reporter.js
  package.json
  test/config.js
  test/instrumentation/_shared-promise-tests.js
  test/instrumentation/async-await.js
  test/instrumentation/index.js
  test/instrumentation/modules/apollo-server-express.js
  test/instrumentation/modules/express-graphql.js
  test/instrumentation/modules/express-queue.js
  test/instrumentation/modules/fastify/async-await.js
  test/instrumentation/modules/fastify/fastify.js
  test/instrumentation/modules/hapi/set-framework-2.js
  test/instrumentation/modules/hapi/set-framework.js
  test/instrumentation/modules/hapi/shared.js
  test/instrumentation/modules/http/github-423.js
  test/instrumentation/modules/http2.js
  test/instrumentation/modules/koa-router/shared.js
  test/instrumentation/modules/mongodb-core.js
  test/instrumentation/modules/mysql2/mysql.js
  test/instrumentation/modules/mysql2/pool-release-1.js
  test/instrumentation/modules/pg/knex.js
  test/instrumentation/modules/pg/pg.js
  test/instrumentation/modules/restify/basic.js
  test/instrumentation/modules/restify/set-framework.js
  test/instrumentation/modules/ws.js
  test/instrumentation/native-promises.js
  test/metrics/index.js
  test/parsers.js
  test/script/run_tests.sh
Labels: [zube]: In Review, breaking change

#1384 fix(package): bump dependencies
  lib/config.js
  package.json
Labels: [zube]: In Progress, breaking change

#1395 docs: add missing breakdownMetrics option
  docs/configuration.asciidoc
Labels: [zube]: In Review, backport:2.x, docs

#1397 docs: fix 'added in' for span API docs
  docs/span-api.asciidoc
Labels: [zube]: In Review, backport:2.x, docs

#1394 [2.x] fix: support all falsy return values from error filters (#1389)
  lib/agent.js
  test/agent.js
Labels: backport

#1396 [2.x] docs: add missing breakdownMetrics option (#1395)
  docs/configuration.asciidoc
Labels: backport

#1398 [2.x] docs: fix 'added in' for span API docs (#1397)
  docs/span-api.asciidoc
Labels: backport

#1400 ci(jenkins): time out problematic test if running too long
  test/instrumentation/modules/http/aborted-requests-enabled.js
Labels: [zube]: In Review, backport:2.x, ci

#1399 docs: fix 'added in' for transaction+agent API docs
  docs/agent-api.asciidoc
  docs/transaction-api.asciidoc
Labels: [zube]: In Review, backport:2.x, docs

#1401 docs(changelog): update changelog from 2.x branch
  CHANGELOG.md
Labels: [zube]: In Review, docs

#1402 ci(jenkins): don't suppress Node.js 6 errors
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#1404 [2.x] docs: fix 'added in' for transaction+agent API docs (#1399)
  docs/agent-api.asciidoc
  docs/transaction-api.asciidoc
Labels: backport

#1403 [2.x] ci(jenkins): time out problematic test if running too long (#1400)
  test/instrumentation/modules/http/aborted-requests-enabled.js
Labels: backport

#1406 fix(package): update read-pkg-up to version 7.0.0
  lib/config.js
  package.json
Labels: [zube]: In Review

#1409 ci(jenkins): end test properly even if it times out
  test/instrumentation/modules/http/aborted-requests-enabled.js
Labels: [zube]: In Review, backport:2.x, ci

#1408 docs: add upgrade guide from v2 to v3
  docs/upgrade-to-v3.asciidoc
  docs/upgrading.asciidoc
Labels: [zube]: In Review, docs

#1388 docs: update CONTRIBUTING.md with new publish guidelines
  CONTRIBUTING.md
Labels: [zube]: In Review, docs

#1410 [2.x] ci(jenkins): end test properly even if it times out (#1409)
  test/instrumentation/modules/http/aborted-requests-enabled.js
Labels: backport

#1412 chore: don't use parseUrl fallback anymore
  lib/instrumentation/express-utils.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/modules/http2.js
  lib/parsers.js
  test/central-config-enabled.js
Labels: [zube]: In Review

#1413 chore: remove deprecated APIs
  docs/agent-api.asciidoc
  docs/redirects.asciidoc
  docs/span-api.asciidoc
  docs/transaction-api.asciidoc
  docs/upgrade-to-v3.asciidoc
  index.d.ts
  lib/agent.js
  lib/instrumentation/generic-span.js
  test/agent.js
Labels: [zube]: In Review, breaking change

#1415 docs: update Node.js release schedule graphic
  docs/images/node_release_schedule.png
  docs/images/node_release_schedule.svg
  docs/supported-technologies.asciidoc
Labels: [zube]: In Review, docs

#1416 ci(jenkins): enable commit lint
  .ci/scripts/test_basic.sh
  test/lint-commits.sh
Labels: automation, ci

#1417 workaround(s) to suppress DEP0066 warnings
  lib/instrumentation/http-shared.js
  lib/instrumentation/modules/http.js
Labels: [zube]: In Review, backport:2.x, enhancement
