Repository elastic/apm-agent-nodejs, pull requests merged in 2020-02, with the labels that each got.

#1614 ci(jenkins): cache docker images in the CI workers
  .ci/packer_cache.sh
  .ci/scripts/test.sh
Labels: automation, ci

#1637 [docs] Add EOL table
  CONTRIBUTING.md
  docs/upgrading.asciidoc
Labels: docs

#1616 test(graphql): test transaction have name for sub-queries
  test/instrumentation/modules/apollo-server-express.js
Labels: [zube]: In Review

#1638 ci(jenkins): run opbeans validation per PR
  .ci/Jenkinsfile
Labels: automation, ci

#1651 [2.x] fix(package): bump require-in-the-middle to ^5.0.2 (#1544)
  package.json
Labels: backport

#1652 [2.x] docs: add @hapi/hapi v19.x to support matrix (#1643)
  docs/supported-technologies.asciidoc
Labels: backport

#1653 [2.x] chore: bump copyright year (#1648)
  LICENSE
Labels: backport

#1654 ci(jenkins): mount ref repo in the docker container
  .ci/Jenkinsfile
Labels: automation, bug, ci

#1655 [2.x] Update asciidoc changelog and remove markdown changelog
  CHANGELOG.asciidoc
  CHANGELOG.md
Labels: docs

#1656 docs: fix CHANGELOG to refence backported PRs
  CHANGELOG.asciidoc
Labels: docs

#1657 docs: fix npm dist-tag used when publishing old versions
  CONTRIBUTING.md
Labels: docs

#1658 docs: align how dates are written in CHANGELOG
  CHANGELOG.asciidoc
Labels: docs

#1659 docs: update CHANGELOG with 2.x changes
  CHANGELOG.asciidoc
Labels: docs

#1650 [docs] Add distributed tracing guide
  docs/distributed-tracing.asciidoc
  docs/index.asciidoc
  docs/transaction-api.asciidoc
Labels: docs

#1663 ci(jenkins): apm-its-downstream params has changed
  .ci/Jenkinsfile
Labels: automation
