Repository elastic/apm-agent-nodejs, pull requests merged in 2020-11, with the labels that each got.

#1848 ci: skip TAP/JUnit and codecov processing for TAV tests
  .ci/Jenkinsfile
Labels: [zube]: In Review

#1853 doc: improve doc comment on _mock_http_client
  test/_mock_http_client.js
Labels: docs

#1858 tests(hapi): do not test hapi@<=v15 on node >=v14
  .tav.yml
Labels: [zube]: In Review

#1846 fix(pg): prevent unhandled promise rejection
  lib/instrumentation/modules/pg.js
  test/instrumentation/modules/pg/pg.js
Labels: [zube]: Backlog

#1868 fix: tests correct codepath for pg span ending
  test/instrumentation/modules/pg/pg.js
Labels: [zube]: In Review

#1865 chore: avoid accidental published files with "files"
  .npmignore
  package.json
Labels: [zube]: In Review

#1873 test: synchronizing json spec
  test/fixtures/json-specs/sql_signature_examples.json
  test/fixtures/json-specs/sql_token_examples.json
  test/fixtures/json-specs/wildcard_matcher_tests.json
Labels: agent-nodejs, automation

#1876 feat: transaction_ignore_urls wildcard matching
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  index.d.ts
  lib/config.js
  lib/instrumentation/http-shared.js
  lib/wildcard-matcher.js
  package.json
  test/central-config-enabled.js
  test/config.js
  test/instrumentation/modules/http/blacklisting.js
  test/wildcard-matcher.js
Labels: agent-nodejs

#1885 chore: grammar/typo fixes
  docs/configuration.asciidoc
  lib/wildcard-matcher.js
Labels: agent-nodejs

#1886 Closes #1834 fix: Treat set-cookie in response headers as sensitive data
  lib/filters/http-headers.js
  test/filters.js
Labels: agent-nodejs

#1894 docs: add changelog to PR checklist
  .github/pull_request_template.md
Labels: agent-nodejs

#1893 feat: set "destination" context for "mongodb" instrumentation
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/mongodb.js
  test/instrumentation/modules/mongodb.js
Labels: agent-nodejs

#1891 feat: support fastify 3
  CHANGELOG.asciidoc
  lib/instrumentation/modules/fastify.js
Labels: agent-nodejs

#1899 chore: have a visible 'Unreleased' section in changelog
  CHANGELOG.asciidoc
  CONTRIBUTING.md
Labels: agent-nodejs

#1900 3.9.0
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  package.json
Labels: agent-nodejs
