Repository elastic/apm-agent-nodejs, pull requests merged in 2020-05, with the labels that each got.

#1738 test: add missing APM Server API Schema file cloud.json
  test/integration/api-schema/download-json-schemas.sh
Labels: backport:1.x, backport:2.x

#1740 [2.x] test: fix APM Server cert test to work with 13.9.0+ (c3c119b1) | test: add missing APM Server API Scheme file cloud.json (#1738)
  test/integration/allow-invalid-cert.js
  test/integration/api-schema/download-json-schemas.sh
Labels: backport

#1726 docs: hint how to ignore spans if very short
  docs/performance-tuning.asciidoc
Labels: docs

#1745 ci: retry to grab the worker IP
  .ci/Jenkinsfile
Labels: bug, ci

#1742 feat: add support for Node.js 14
  .ci/.jenkins_nightly_nodejs.yml
  .ci/.jenkins_nodejs.yml
  .ci/.jenkins_rc_nodejs.yml
  .ci/.jenkins_tav_nodejs.yml
  .tav.yml
  .travis.yml
  package.json
Labels: [zube]: In Review

#1682 [2.x] chore(package): bump standard to version ^14.3.3 (#1677)
  package.json
Labels: backport

#1683 [2.x] fix(package): bump stackman to ^4.0.1 (#1679)
  package.json
Labels: backport

#1751 ci: remove unused job
  .ci/downstreamTests.groovy
  .ci/jobs/apm-agent-nodejs-downstream.yml
Labels: automation, ci

#1757 ci(jenkins): debug windows worker reqs
  .ci/Jenkinsfile
Labels: automation, bug, ci
