Repository elastic/apm-agent-nodejs, pull requests merged in 2020-03, with the labels that each got.

#1393 ci(jenkins): support windows build
  .appveyor.yml
  .ci/Jenkinsfile
  .ci/scripts/windows/prepare-test.sh
  .ci/scripts/windows/stop-test.sh
  .gitignore
  test/agent.js
  test/config.js
  test/instrumentation/modules/bluebird/bluebird.js
  test/instrumentation/modules/pg/_utils.js
  test/instrumentation/modules/pg/knex.js
  test/instrumentation/modules/pg/pg.js
  test/script/appveyor/install-cassandra.ps1
  test/script/appveyor/install-elasticsearch.ps1
  test/script/appveyor/install-redis.ps1
Labels: [zube]: Inbox, automation, ci

#1665 [2.x] ci(jenkins): support windows (#1393)
  .appveyor.yml
  .ci/Jenkinsfile
  .ci/scripts/windows/prepare-test.sh
  .ci/scripts/windows/stop-test.sh
  .gitignore
  test/agent.js
  test/config.js
  test/instrumentation/modules/bluebird/bluebird.js
  test/instrumentation/modules/pg/_utils.js
  test/instrumentation/modules/pg/knex.js
  test/instrumentation/modules/pg/pg.js
  test/script/appveyor/install-cassandra.ps1
  test/script/appveyor/install-elasticsearch.ps1
  test/script/appveyor/install-redis.ps1
Labels: backport

#1670 docs: fix typo in CHANGELOG.asciidoc
  CHANGELOG.asciidoc
Labels: docs

#1680 docs: add entry about Jenkins magic PR comments to TESTING.md
  TESTING.md
Labels: docs

#1691 docs: Add link to Agent/Server compatibility
  docs/intro.asciidoc
Labels: docs

#1694 ci(jenkins): disable stages for only docs
  .ci/Jenkinsfile
Labels: automation

#1702 ci(jenkins): use nodejs lts in the windows stage
  .ci/Jenkinsfile
Labels: automation, ci

#1704 [3.x] ci(jenkins): use nodejs lts in the windows stage (#1702) (7b933627)
  .ci/Jenkinsfile
Labels: automation, backport

#1703 [2.x] ci(jenkins): use nodejs lts in the windows stage (#1702) (7b933627)
  .ci/Jenkinsfile
Labels: automation, backport
