Repository elastic/apm-agent-nodejs, pull requests merged in 2021-11, with the labels that each got.

#2333 fix: adapt logger.child call to new pino 6 format
  CHANGELOG.asciidoc
  lib/logging.js
Labels: agent-nodejs, community

#2396 feat: impl contextPropagationOnly config var; change disableSend behaviour
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  index.d.ts
  lib/agent.js
  lib/config.js
  lib/instrumentation/index.js
  lib/instrumentation/transaction.js
  lib/metrics/index.js
  lib/noop-transport.js
  test/config.test.js
  test/context-propagation-only.test.js
  test/disable-send.test.js
Labels: agent-nodejs

#2413 synchronize schema spec
  test/integration/api-schema/apm-server-schema/error.json
Labels: automation, agent-nodejs

#2421 docs: clarify side-effects of 'captureExceptions: true'
  docs/configuration.asciidoc
Labels: agent-nodejs

#2410 feat: zero-configuration support by always successfully inferring a serviceName
  CHANGELOG.asciidoc
  docs/agent-api.asciidoc
  docs/configuration.asciidoc
  lib/agent.js
  lib/config.js
  lib/instrumentation/index.js
  lib/logging.js
  package.json
  test/agent.test.js
  test/config.test.js
  test/filters.test.js
  test/fixtures/pkg-zero-conf-noname/index.js
  test/fixtures/pkg-zero-conf-noname/package.json
  test/fixtures/pkg-zero-conf-nsname/index.js
  test/fixtures/pkg-zero-conf-nsname/package.json
  test/fixtures/pkg-zero-conf-sanitize/index.js
  test/fixtures/pkg-zero-conf-sanitize/package.json
  test/fixtures/pkg-zero-conf-valid/index.js
  test/fixtures/pkg-zero-conf-valid/package.json
  test/fixtures/pkg-zero-conf-weird/index.js
  test/fixtures/pkg-zero-conf-weird/package.json
  test/redact-secrets/is-secret.test.js
  test/redact-secrets/redact-secrets.test.js
  test/start/env/test.test.js
  test/start/file/test.test.js
Labels: agent-nodejs

#2194 feat: lambda faas transaction properties and cold start detection
  CHANGELOG.asciidoc
  lib/constants.js
  lib/instrumentation/transaction.js
  lib/lambda.js
  test/instrumentation/transaction.test.js
  test/lambda/_util.js
  test/lambda/fixtures/aws_api_http_test_data.json
  test/lambda/fixtures/aws_api_rest_test_data.json
  test/lambda/fixtures/aws_s3_batch_test_data.json
  test/lambda/fixtures/aws_s3_test_data.json
  test/lambda/fixtures/aws_sns_test_data.json
  test/lambda/fixtures/aws_sqs_test_data.json
  test/lambda/fixtures/context.json
  test/lambda/fixtures/generic.json
  test/lambda/mock/transaction.js
  test/lambda/transaction.test.js
Labels: agent-nodejs

#2407 feat: gather AWS Lambda metadata on first function invocation
  CHANGELOG.asciidoc
  lib/cloud-metadata/index.js
  lib/cloud-metadata/lambda.js
  lib/config.js
  lib/lambda.js
  lib/noop-transport.js
  package.json
  test/_capturing_transport.js
  test/cloud-metadata/index.test.js
  test/lambda/cloud-metadata.test.js
  test/lambda/metadata.test.js
Labels: agent-nodejs

#2422 fix: remove unspec'd custom context for lambda transactions
  lib/lambda.js
  test/lambda/_util.js
  test/lambda/callbacks.test.js
  test/lambda/context.test.js
  test/lambda/promises.test.js
Labels: agent-nodejs

#2428 fix: apm.startTransaction() crash if agent not yet started
  lib/agent.js
  lib/config.js
  test/agent.test.js
Labels: agent-nodejs

#2434 chore: update Lambda trans.context.service.origin.name
  lib/lambda.js
  test/lambda/metadata.test.js
  test/lambda/transaction.test.js
Labels: agent-nodejs

#2426 docs: new lambda docs for Node.js agent
  docs/lambda.asciidoc
  docs/set-up.asciidoc
  docs/supported-technologies.asciidoc
Labels: agent-nodejs

#2435 3.24.0
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  package.json
Labels: agent-nodejs

#2431 chore: use race neutral language
  lib/instrumentation/http-shared.js
  test/config.test.js
  test/instrumentation/modules/http/ignoring.test.js
Labels: agent-nodejs

#2436 chore: fix typo in internal function name
  lib/config.js
  lib/lambda.js
  test/lambda/metadata.test.js
Labels: agent-nodejs

#2432 chore: deprecate `transaction.subtype` and `transaction.action`
  CHANGELOG.asciidoc
  docs/agent-api.asciidoc
  docs/transaction-api.asciidoc
  index.d.ts
  lib/instrumentation/transaction.js
  test/instrumentation/transaction.test.js
  test/outcome.test.js
Labels: agent-nodejs

#2438 refactor: drop unused 'npm run test:cli'; add test for apm.middleware.connect()
  lib/instrumentation/modules/finalhandler.js
  package.json
  test/connect.test.js
  test/script/cli.js
Labels: agent-nodejs

#2439 fix: memoryLimitInMB made string to comply with @types/aws-lambda
  types/aws-lambda.d.ts
Labels: agent-nodejs, community

#2442 fix: do not set 'tracestate' header to the empty string
  CHANGELOG.asciidoc
  lib/instrumentation/http-shared.js
Labels: agent-nodejs

#2445 refactor: improve test case messages and correctness in redis test
  test/instrumentation/modules/redis.test.js
Labels: agent-nodejs

#2452 fix: no need to escape chars in serviceName for User-Agent
  lib/config.js
  test/config.test.js
Labels: agent-nodejs

#2447 tests: fix failing restify tests with latest node v18.0.0 nightly
  test/config.test.js
  test/instrumentation/modules/fastify/set-framework.test.js
  test/instrumentation/modules/restify/basic.test.js
  test/instrumentation/modules/restify/set-framework.test.js
  test/sanitize-field-names/restify.test.js
Labels: agent-nodejs

#2446 fix: offline-queued redis commands would be double-instrumented
  CHANGELOG.asciidoc
  lib/instrumentation/modules/redis.js
  package.json
  test/instrumentation/modules/redis.test.js
Labels: agent-nodejs

#2457 fix: redis run-context handling, error capture, span.outcome
  CHANGELOG.asciidoc
  examples/trace-redis.js
  lib/instrumentation/modules/redis.js
  test/instrumentation/modules/redis.test.js
Labels: agent-nodejs

#2461 Fixing broken link to AWS Lambda Extension documentation
  docs/lambda.asciidoc
Labels: agent-nodejs

#2462 fix: the error captured for an erroring redis span should be the span
  lib/instrumentation/modules/redis.js
  test/instrumentation/modules/redis.test.js
Labels: agent-nodejs

#2463 fix: ensure run-context for mysql span does not spill into user code
  CHANGELOG.asciidoc
  examples/trace-mysql.js
  lib/instrumentation/modules/mysql.js
  test/instrumentation/modules/mysql/mysql.test.js
Labels: agent-nodejs

#2448 ci: support modules github comments
  .ci/Jenkinsfile
  README.md
Labels: agent-nodejs

#2466 3.25.0
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  package.json
  test/instrumentation/modules/@elastic/elasticsearch.test.js
Labels: agent-nodejs

#2460 fix: rewrite ioredis instrumentation: run-context, add destination context, captureError
  .tav.yml
  CHANGELOG.asciidoc
  examples/trace-ioredis.js
  lib/instrumentation/modules/ioredis.js
  package.json
  test/instrumentation/modules/ioredis.test.js
Labels: agent-nodejs

#2476 [jjbb] add minor improvements
  .ci/jobs/apm-agent-nodejs-mbp.yml
  .ci/jobs/defaults.yml
Labels: agent-nodejs
