Repository elastic/apm-agent-nodejs, pull requests merged in 2021-03, with the labels that each got.

#1994 test: fix test end handling when http client is using keep-alive agent
  test/central-config-enabled.js
Labels: agent-nodejs

#1993 chore: drop unused 'nodejs.eventloop.delay.ns' metric
  CHANGELOG.asciidoc
  lib/metrics/runtime.js
  test/metrics/breakdown.js
Labels: agent-nodejs

#1998 ci: skip packer cache on ARM
  .ci/packer_cache.sh
Labels: agent-nodejs, automation, ci

#2003 fix: crash on start if trace-logging and no process.argv[1]
  lib/agent.js
Labels: agent-nodejs

#2005 chore: drop ancestors trace log (it adds nothing over 'startTrace' info) and the dep for it
  CHANGELOG.asciidoc
  lib/agent.js
  package.json
Labels: agent-nodejs

#2008 feat: ignore_message_queues configuration
  docs/configuration.asciidoc
  index.d.ts
  lib/config.js
  test/config.js
Labels: agent-nodejs

#2001 feat: pino logging
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  docs/fastify.asciidoc
  docs/troubleshooting.asciidoc
  lib/agent.js
  lib/config.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/bluebird.js
  lib/instrumentation/modules/express.js
  lib/instrumentation/modules/http2.js
  lib/instrumentation/modules/knex.js
  lib/instrumentation/modules/mongodb-core.js
  lib/instrumentation/shimmer.js
  lib/lambda.js
  lib/logging.js
  package.json
  test/config.js
  test/instrumentation/_agent.js
  test/logging.js
Labels: agent-nodejs

#2017 test: skip testing @elastic/elasticsearch >= 7.12.0 with node 8
  .tav.yml
  test/config.js
  test/instrumentation/modules/@elastic/elasticsearch.js
Labels: agent-nodejs

#2015 pass a logger to the apmclient and private _getStats for debugging
  lib/agent.js
  lib/config.js
Labels: agent-nodejs

#2004 feat(koa-router): add support to @koa/router version 10
  .tav.yml
  lib/instrumentation/modules/koa-router.js
Labels: agent-nodejs

#2025 fix: workaround to a git <2.7 issue
  .ci/scripts/docker-test.sh
Labels: agent-nodejs, automation, bug, ci
