Repository elastic/apm-agent-nodejs, pull requests merged in 2021-04, with the labels that each got.

#2033 3.13.0
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  package.json
Labels: agent-nodejs

#2013 feature: sqs queue instrumentation
  .tav.yml
  CHANGELOG.asciidoc
  docs/index.asciidoc
  docs/message-queues.asciidoc
  docs/supported-technologies.asciidoc
  lib/agent.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/aws-sdk.js
  lib/instrumentation/modules/aws-sdk/sqs.js
  lib/instrumentation/span.js
  lib/metrics/index.js
  lib/metrics/queue.js
  test/agent.js
  test/instrumentation/modules/aws-sdk/fixtures-sqs.js
  test/instrumentation/modules/aws-sdk/sqs.js
  test/instrumentation/span.js
  test/test.js
Labels: agent-nodejs

#2037 fix: fixes crash when accessing values from invalid tracestates
  lib/tracecontext/tracestate.js
  test/tracecontext/tracestate.js
Labels: agent-nodejs

#2043 test: edge jenkins tests ("Nightly" and "RC") were broken
  .ci/docker/node-edge-container/Dockerfile
Labels: agent-nodejs

#2041 synchronize schema spec
  test/integration/api-schema/apm-server-schema/error.json
  test/integration/api-schema/apm-server-schema/metadata.json
  test/integration/api-schema/apm-server-schema/transaction.json
Labels: agent-nodejs, automation

#2036 docs: start an informal doc for dev tips
  DEVELOPMENT.md
Labels: agent-nodejs

#2024 fix: blocking behaviour under load
  CHANGELOG.asciidoc
  docs/agent-api.asciidoc
  docs/configuration.asciidoc
  docs/performance-tuning.asciidoc
  index.d.ts
  lib/config.js
  package.json
  test/_apm_server.js
  test/agent.js
  test/config.js
  test/integration/api-schema/basic.js
  test/integration/api-schema/capture-error-log-stack-traces.js
  test/integration/api-schema/capture-span-stack-traces.js
  test/integration/api-schema/source-lines-error-frames.js
  test/integration/api-schema/source-lines-span-frames.js
Labels: agent-nodejs

#2038 feat: add sample_rate to spans and transactions
  CHANGELOG.asciidoc
  lib/instrumentation/generic-span.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  lib/tracecontext/index.js
  test/instrumentation/span.js
  test/instrumentation/transaction.js
  test/tracecontext/sample_rate.js
Labels: agent-nodejs

#2045 feat: add apm.addMetadataFilter(fn)
  CHANGELOG.asciidoc
  docs/agent-api.asciidoc
  index.d.ts
  lib/agent.js
  package.json
  test/agent.js
  test/types/index.ts
Labels: agent-nodejs

#2039 fix: span url hostname not ip
  CHANGELOG.asciidoc
  lib/instrumentation/http-shared.js
  package.json
  test/instrumentation/modules/http/outgoing.js
  test/instrumentation/modules/http/request-to-url.js
Labels: agent-nodejs

#2046 test: synchronizing json spec
  test/fixtures/json-specs/sql_token_examples.json
Labels: agent-nodejs, automation

#2049 chore: drop codecov.io usage
  .ci/Jenkinsfile
  .ci/scripts/docker-test.sh
  .codecov.yml
  .github/workflows/test.yml
  .gitignore
  package.json
  test/script/docker/run_tests.sh
Labels: agent-nodejs

#2051 3.14.0
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  package.json
Labels: agent-nodejs

#2048 tests: drop lingering support for junit output
  test/script/docker/run_tests.sh
  test/script/run_tests.sh
Labels: agent-nodejs

#2052 Update setup.asciidoc
  docs/setup.asciidoc
Labels: agent-nodejs, docs

#2059 chore: drop unused createFilter function
  lib/filters/sanitize-field-names.js
Labels: agent-nodejs

#2058 fix: get the benchmarks run in CI to stick to a constant major ver of node
  .ci/Jenkinsfile
  .ci/scripts/prepare-benchmarks-env.sh
  .ci/scripts/run-benchmarks.sh
  test/benchmarks/scripts/run-benchmarks-ci.sh
  test/benchmarks/scripts/run-benchmarks.sh
Labels: agent-nodejs

#2060 ci: CI docker TAV tests are unnecessarily setting up all services for some modules
  .ci/Jenkinsfile
  .ci/docker/docker-compose-node-edge-test.yml
  .ci/docker/docker-compose-node-test.yml
  .ci/scripts/test.sh
  test/script/docker/run_tests.sh
Labels: agent-nodejs
