Repository elastic/apm-agent-nodejs, pull requests merged in 2021-06, with the labels that each got.

#2096 synchronize schema spec
  test/integration/api-schema/apm-server-schema/metricset.json
Labels: agent-nodejs, automation

#2097 fix: missing typescript defs
  docs/configuration.asciidoc
  index.d.ts
Labels: agent-nodejs

#2081 perf: don't collect stack traces on short spans
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  docs/performance-tuning.asciidoc
  index.d.ts
  lib/config.js
  lib/instrumentation/generic-span.js
  lib/instrumentation/span.js
  test/instrumentation/_agent.js
  test/instrumentation/async-hooks.js
  test/instrumentation/index.js
  test/instrumentation/modules/@elastic/elasticsearch.js
  test/instrumentation/modules/apollo-server-express.js
  test/instrumentation/modules/cassandra-driver/index.js
  test/instrumentation/modules/elasticsearch.js
  test/instrumentation/modules/express-graphql.js
  test/instrumentation/modules/handlebars.js
  test/instrumentation/modules/http/disabling.js
  test/instrumentation/modules/ioredis.js
  test/instrumentation/modules/jade.js
  test/instrumentation/modules/pg/knex.js
  test/instrumentation/modules/pug.js
  test/span-frames-min-duration.js
Labels: agent-nodejs, performance

#2094 perf: refactor error capture and stacktrace collection
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  lib/agent.js
  lib/errors.js
  lib/instrumentation/span.js
  lib/parsers.js
  lib/stackman.js
  lib/stacktraces.js
  package.json
  test/agent.js
  test/config.js
  test/errors.test.js
  test/instrumentation/modules/apollo-server-express.js
  test/instrumentation/modules/express-graphql.js
  test/parsers.js
  test/stacktraces/_mock_apm_server.js
  test/stacktraces/fixtures/Makefile
  test/stacktraces/fixtures/capture-error-string.js
  test/stacktraces/fixtures/circular-stack.js
  test/stacktraces/fixtures/dist/throw-an-error-with-sourcemap.js
  test/stacktraces/fixtures/dist/throw-an-error-with-sourcemap.js.map
  test/stacktraces/fixtures/send-a-span.js
  test/stacktraces/fixtures/src/throw-an-error-with-sourcemap.ts
  test/stacktraces/fixtures/throw-an-error.js
  test/stacktraces/fixtures/tsconfig.json
  test/stacktraces/stacktraces.test.js
  test/test.js
  test/uncaught-exceptions/log-uncaught-exceptions-off.js
Labels: agent-nodejs, performance

#2107 fix: 'TypeError: lastPrepareStackTrace' crash when used with React v17+
  CHANGELOG.asciidoc
  package.json
Labels: agent-nodejs

#2104 perf: bump elastic-apm-http-client dep to 9.8.1 to get minor perf tweak
  package.json
Labels: agent-nodejs

#2108 3.16.0
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  package.json
Labels: agent-nodejs

#2105 fix: use subtype=http and action=$method for all HTTP spans
  CHANGELOG.asciidoc
  lib/instrumentation/http-shared.js
  lib/instrumentation/modules/http2.js
  test/instrumentation/modules/@elastic/elasticsearch.js
  test/instrumentation/modules/elasticsearch.js
  test/instrumentation/modules/http/disabling.js
  test/instrumentation/modules/http2.js
Labels: agent-nodejs

#2111 fix: avoid possible circular require bug between this and ecs-pino-format
  package.json
Labels: agent-nodejs

#2117 synchronize schema spec
  test/integration/api-schema/apm-server-schema/span.json
Labels: agent-nodejs, automation

#2114 fix: SQS crashing error with no active transaction
  CHANGELOG.asciidoc
  lib/instrumentation/modules/aws-sdk/sqs.js
  test/instrumentation/modules/aws-sdk/sqs.js
Labels: agent-nodejs

#2122 docs: improve changelog note on sanitize_field_names
  CHANGELOG.asciidoc
Labels: agent-nodejs

#2123 ci: drop testing with node v15
  .ci/.jenkins_nodejs.yml
  .ci/.jenkins_rc_nodejs.yml
  .ci/.jenkins_tav_nodejs.yml
  .github/workflows/test.yml
Labels: agent-nodejs

#2112 feat: AWS S3 instrumentation
  .ci/Jenkinsfile
  .ci/docker/docker-compose-all.yml
  .ci/docker/docker-compose-edge.yml
  .ci/docker/docker-compose-localstack.yml
  .ci/docker/docker-compose-node-edge-test.yml
  .ci/docker/docker-compose-node-test.yml
  .ci/docker/docker-compose.yml
  .ci/scripts/docker-test.sh
  .ci/scripts/test.sh
  .github/workflows/test.yml
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  lib/agent.js
  lib/instrumentation/modules/aws-sdk.js
  lib/instrumentation/modules/aws-sdk/s3.js
  package.json
  test/_mock_apm_server.js
  test/docker-compose.ci.yml
  test/docker-compose.yml
  test/instrumentation/modules/aws-sdk/fixtures/use-s3.js
  test/instrumentation/modules/aws-sdk/s3.test.js
  test/instrumentation/modules/aws-sdk/sqs.js
  test/script/local-deps-start.sh
  test/script/local-deps-stop.sh
  test/stacktraces/stacktraces.test.js
Labels: agent-nodejs

#2133 tests: fix mssql server Docker registry
  .ci/docker/docker-compose.yml
  .github/workflows/test.yml
  test/docker-compose.yml
Labels: agent-nodejs

#2126 Fix #1770 support for proxies in destination context
  CHANGELOG.asciidoc
  lib/instrumentation/http-shared.js
  test/instrumentation/github-issue-1770.js
Labels: agent-nodejs, bug

#2132 tests: fix docker-compose setup that broke aws-sdk TAV tests in CI
  .ci/docker/docker-compose-localstack.yml
Labels: agent-nodejs

#2127 feat: disableSend boolean config option to work, but not communicate with APM server
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  index.d.ts
  lib/agent.js
  lib/config.js
  lib/errors.js
  lib/instrumentation/index.js
  lib/instrumentation/transaction.js
  lib/metrics/index.js
  lib/noop-transport.js
  package.json
  test/config.js
  test/disable-send.test.js
Labels: agent-nodejs

#2130 chore: ensure no logging during benchmark runs which can break analysis
  test/benchmarks/utils/bench.js
Labels: agent-nodejs

#2136 tests: run S3 tests with each aws-sdk TAV version test
  .tav.yml
Labels: agent-nodejs
