Repository elastic/apm-agent-nodejs, pull requests merged in 2021-05, with the labels that each got.

#2069 chore: don't run GH Actions CI lint and tests for .md and doc file changes
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: agent-nodejs

#2068 docs: dev note on running the Benchmark suite in Jenkins
  DEVELOPMENT.md
Labels: agent-nodejs

#2063 fix: remove passthrough props in tracecontext
  lib/agent.js
  lib/instrumentation/generic-span.js
  lib/tracecontext/index.js
  test/agent.js
  test/instrumentation/modules/http/basic.js
  test/instrumentation/span.js
  test/instrumentation/transaction.js
Labels: agent-nodejs, performance

#2066 fix: remove .entries and Object.entries in for loops to improve flamegraph perf
  lib/tracecontext/tracestate.js
Labels: agent-nodejs

#2073 refactor: clarify func name
  lib/parsers.js
Labels: agent-nodejs

#2072 test: ensure sanitizeFieldNames is applied to captured errors
  test/agent.js
Labels: agent-nodejs

#2070 chore: remove unnecessary re-calculation in benchmark reporter
  test/benchmarks/utils/result-logger.js
Labels: agent-nodejs

#1971 tav: docker-compose down with orphans and no fail
  .ci/scripts/test.sh
Labels: agent-nodejs, automation, ci

#2077 fix: add 'stringify' arg to TypeScript typings for setLabel and addLabels
  CHANGELOG.asciidoc
  index.d.ts
  test/types/index.ts
Labels: agent-nodejs

#2074 fix: drop obsolete .context.user.is_authenticated field
  lib/parsers.js
Labels: agent-nodejs

#2078 3.15.0
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  package.json
Labels: agent-nodejs

#2079 feat: prefer 'traceparent' header over 'elastic-apm-traceparent' header
  CHANGELOG.asciidoc
  lib/instrumentation/http-shared.js
Labels: agent-nodejs

#2086 test: correct the sense of ELASTIC_APM_ASYNC_HOOKS envvar from disableAsyncHooks jenkins step option
  .ci/Jenkinsfile
Labels: agent-nodejs

#2087 test: limit testing of 'edge' node builds (node.js nightly and RC builds) to useful versions
  .ci/.jenkins_nightly_nodejs.yml
  .ci/.jenkins_rc_nodejs.yml
  .ci/Jenkinsfile
  .ci/scripts/test.sh
Labels: agent-nodejs

#2093 test: make this test robust for additional capture spans possible with mongodb-core@1.x
  DEVELOPMENT.md
  test/instrumentation/modules/mongodb-core.js
Labels: agent-nodejs

#2091 test: faster TAV runs by reducing the test matrix
  .ci/.jenkins_tav.yml
  .tav.yml
Labels: agent-nodejs
