Repository elastic/apm-agent-nodejs, pull requests merged in 2021-12, with the labels that each got.

#2470 fix: ensure the span run-context for outgoing http requests does not spill into user code
  CHANGELOG.asciidoc
  examples/trace-http-request.js
  examples/trace-http.js
  lib/http-request.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/https.js
  test/instrumentation/modules/http/fixtures/make-http-request.js
  test/instrumentation/modules/http/fixtures/make-https-request.js
  test/instrumentation/modules/http/http-run-context.test.js
Labels: agent-nodejs

#2468 tests: fix benchmark config to not skip span.stacktrace collection
  test/benchmarks/002-transaction-and-span-overhead-realistic-size.js
Labels: agent-nodejs

#2472 fix: ensure correct run-context for instrumented aws-sdk client usage
  CHANGELOG.asciidoc
  lib/instrumentation/modules/aws-sdk/s3.js
  lib/instrumentation/modules/aws-sdk/sns.js
  lib/instrumentation/modules/aws-sdk/sqs.js
  test/instrumentation/modules/aws-sdk/fixtures/sqs.js
  test/instrumentation/modules/aws-sdk/fixtures/use-s3.js
  test/instrumentation/modules/aws-sdk/s3.test.js
  test/instrumentation/modules/aws-sdk/sns.test.js
  test/instrumentation/modules/aws-sdk/sqs.test.js
Labels: agent-nodejs

#2473 tests: reduce the number of versions of jade being tested
  .tav.yml
  examples/trace-handlebars.js
  examples/trace-pug.js
Labels: agent-nodejs

#2480 fix: crash in Transaction serialization if req.socket is null
  CHANGELOG.asciidoc
  lib/parsers.js
  test/instrumentation/modules/http2.test.js
Labels: agent-nodejs

#2475 fix: ensure correct run-context for 'memcached' instrumentation
  CHANGELOG.asciidoc
  examples/trace-memcached.js
  lib/instrumentation/modules/memcached.js
  test/instrumentation/modules/memcached.test.js
Labels: agent-nodejs

#2492 test: synchronizing json spec
  test/fixtures/json-specs/span_types.json
Labels: automation, agent-nodejs

#2481 fix: ensure correct run context for 'ws' instrumentation
  CHANGELOG.asciidoc
  examples/trace-ws.js
  lib/instrumentation/modules/ws.js
  test/instrumentation/modules/ws.test.js
Labels: agent-nodejs

#2483 fix: run-context for 'http2.request' instrumentation
  CHANGELOG.asciidoc
  examples/trace-http2-request.js
  lib/instrumentation/modules/http2.js
  test/instrumentation/modules/http2.test.js
Labels: agent-nodejs

#2478 tests: ensure CI test run generates proper junit output files for Jenkins reporting
  .ci/Jenkinsfile
  .ci/scripts/docker-test.sh
  .gitignore
  package.json
  test/script/docker/run_tests.sh
  test/test.js
Labels: agent-nodejs

#2494 fix: ensure correct run-context for "tedious" instrumentation
  CHANGELOG.asciidoc
  examples/trace-tedious.js
  lib/instrumentation/modules/tedious.js
  test/instrumentation/modules/tedious.test.js
Labels: agent-nodejs

#2499 docs: Fix broken link to 7.16 docs
  docs/log-correlation.asciidoc
Labels: agent-nodejs, Team:Docs

#2501 docs: pin 2.x to 7.15
  docs/index.asciidoc
Labels: Team:Docs

#2495 feat: add *auth* pattern to sanitizeFieldNames default
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  lib/config.js
  test/instrumentation/modules/http2.test.js
  test/sanitize-field-names/_fixtures.js
  test/sanitize-field-names/_shared.js
Labels: agent-nodejs

#2487 fix: ensure correct run context for mysql2 instrumentation
  CHANGELOG.asciidoc
  examples/trace-mysql2.js
  lib/instrumentation/modules/mysql2.js
  test/instrumentation/modules/mysql2/mysql.test.js
Labels: agent-nodejs

#2503 perf, docs: avoid calculating breakdown metrics if not sending
  docs/configuration.asciidoc
  docs/metrics.asciidoc
  lib/config.js
Labels: performance, agent-nodejs

#2505 3.26.0
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  package.json
Labels: agent-nodejs

#2504 fix: run context handling for aws-sdk DynamoDB instrumentation
  .tav.yml
  CHANGELOG.asciidoc
  lib/instrumentation/modules/aws-sdk/dynamodb.js
  test/instrumentation/modules/aws-sdk/dynamodb.test.js
Labels: agent-nodejs

#2518 tests: fix TAV=got test failures with got@12
  .tav.yml
Labels: agent-nodejs

#2519 ci: update opbeans branch to main
  .ci/Jenkinsfile
Labels: agent-nodejs

#2521 tests: use www.google.com rather than httpstat.us for an HTTP test
  test/instrumentation/modules/http/fixtures/make-http-request.js
  test/instrumentation/modules/http/http-run-context.test.js
Labels: agent-nodejs

#2520 ci: Update ITs main
  .ci/Jenkinsfile
Labels: automation, agent-nodejs

#2523 synchronize schema spec
  test/integration/api-schema/apm-server-schema/transaction.json
Labels: automation, agent-nodejs

#2522 ci: avoid retagging official node images
  .ci/packer_cache.sh
Labels: automation, agent-nodejs
