Repository elastic/apm-agent-nodejs, pull requests merged in 2022-09, with the labels that each got.

#2904 feat: change log message
  lib/cloud-metadata/callback-coordination.js
Labels: agent-nodejs

#2912 feat(koa): enable koa-router 11/12
  .tav.yml
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/koa-router.js
  package-lock.json
  package.json
  test/config.test.js
  test/instrumentation/modules/koa-router/shared.js
Labels: agent-nodejs, community

#2915 synchronize schema spec
  test/integration/api-schema/apm-server-schema/log.json
Labels: automation, agent-nodejs

#2906 feat: delay loading error-callsites module
  CHANGELOG.asciidoc
  lib/agent.js
  lib/stacktraces.js
  test/stacktraces/fixtures/get-prepare-stacktrace.js
  test/stacktraces/stacktraces.test.js
Labels: agent-nodejs

#2921 chore: drop obsolete test and 'send' dev dep
  package-lock.json
  package.json
  test/instrumentation/github-issue-75.test.js
Labels: agent-nodejs

#2923 chore: reduce freq of dependabot updates for some deps to monthly
  .github/dependabot.yml
Labels: agent-nodejs

#2936 test: lock to mongo:5 container, recently released mongo:6 breaks our healthcheck
  .ci/docker/docker-compose.yml
  .github/workflows/test.yml
  test/docker-compose.yml
Labels: agent-nodejs

#2924 chore: add a dev utility to list issues with instrumention module version ranges
  .tav.yml
  DEVELOPMENT.md
  dev-utils/bitrot.js
  docs/supported-technologies.asciidoc
Labels: agent-nodejs

#2940 ci: remove Integration Tests stage
  .ci/Jenkinsfile
  DEVELOPMENT.md
Labels: agent-nodejs

#2942 test: reduce TAV tested versions of aws-sdk
  .tav.yml
Labels: agent-nodejs

#2949 test: synchronizing json spec
  test/fixtures/json-specs/cgroup_parsing.json
Labels: automation, agent-nodejs
