Repository elastic/apm-agent-nodejs, pull requests merged in 2022-06, with the labels that each got.

#2742 Build docker image
  .ci/Jenkinsfile
  .ci/Makefile
  Dockerfile
  dev-utils/make-distribution.sh
  dev-utils/push-docker.sh
Labels: agent-nodejs

#2746 Fix docker image Jenkins stage
  .ci/Jenkinsfile
Labels: agent-nodejs

#2748 fix: the "Push Docker Image" jenkins step requires a HOME var
  .ci/Jenkinsfile
Labels: agent-nodejs

#2749 chore: move HOME envvar to 'Release' stage closer to where it is needed
  .ci/Jenkinsfile
Labels: agent-nodejs

#2740 Feat: Add support for knex between 0.21 and 0.95.15 included
  .tav.yml
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/knex.js
  test/instrumentation/modules/pg/knex.test.js
Labels: agent-nodejs, community

#2707 feat: dropped span stats
  CHANGELOG.asciidoc
  lib/instrumentation/dropped-span-stats.js
  lib/instrumentation/index.js
  lib/instrumentation/transaction.js
  test/instrumentation/dropped-span-stats.test.js
  test/instrumentation/transaction.test.js
Labels: agent-nodejs

#2750 fix: Express route calc when next(err-that-is-not-Error-instance) is used
  CHANGELOG.asciidoc
  lib/instrumentation/modules/express.js
  test/instrumentation/modules/express/basic.test.js
Labels: agent-nodejs

#2637 feat: fix all env prefixes
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  lib/config.js
  test/config.test.js
Labels: agent-nodejs

#2754 fix: handle wrapping Lambda handlers in modules that only provide getters to the handler properties
  .eslintrc.json
  CHANGELOG.asciidoc
  NOTICE.md
  lib/instrumentation/modules/_lambda-handler.js
  lib/lambda.js
  lib/propwrap.js
  test/lambda/fixtures/esbuild-bundled-handler/Makefile
  test/lambda/fixtures/esbuild-bundled-handler/README.md
  test/lambda/fixtures/esbuild-bundled-handler/hello.js
  test/lambda/fixtures/esbuild-bundled-handler/hello.ts
  test/lambda/wrap-bundled-handler.test.js
  test/lambda/wrapper.test.js
  test/propwrap.test.js
Labels: agent-nodejs

#2762 chore: update testing for fastify@4
  .tav.yml
  docs/supported-technologies.asciidoc
  package-lock.json
  package.json
  test/_is_fastify_incompat.js
  test/config.test.js
  test/instrumentation/modules/fastify/_async-await.js
  test/instrumentation/modules/fastify/async-await.test.js
  test/instrumentation/modules/fastify/fastify.test.js
  test/instrumentation/modules/fastify/set-framework.test.js
  test/sanitize-field-names/fastify.test.js
Labels: agent-nodejs

#2763 chore: drop Opbeans update stage of the CI Release pipeline
  .ci/Jenkinsfile
Labels: agent-nodejs

#2747 Added container image tab to lambda setup docs
  docs/lambda/configure-lambda-widget.asciidoc
  docs/lambda/configure-lambda.asciidoc
  docs/lambda/nodejs-arn-replacement.asciidoc
Labels: agent-nodejs

#2771 test: skip broken fastify@4.0.1 in TAV tests
  .tav.yml
  package-lock.json
  package.json
Labels: agent-nodejs

#2772 feat: add Elasticsearch client API error type to captured error.exception.type for better grouping
  .ci/docker/docker-compose.yml
  .github/workflows/test.yml
  CHANGELOG.asciidoc
  lib/agent.js
  lib/errors.js
  lib/instrumentation/modules/@elastic/elasticsearch.js
  test/docker-compose.yml
  test/instrumentation/modules/@elastic/elasticsearch.test.js
Labels: agent-nodejs

#2776 3.36.0
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  package-lock.json
  package.json
Labels: agent-nodejs

#2764 chore: include NOTICE file in npm published package and in dist
  .ci/Jenkinsfile
  .github/workflows/lint.yml
  dev-utils/gen-notice.sh
  dev-utils/license.MIT.txt
  dev-utils/license.node-measured.txt
  dev-utils/make-distribution.sh
  package.json
Labels: agent-nodejs

#2778 synchronize schema spec
  test/integration/api-schema/apm-server-schema/metricset.json
Labels: automation, agent-nodejs

#2782 Added reference to Secrets Manager section in the lambda docs
  docs/lambda.asciidoc
Labels: agent-nodejs

#2783 docs: drop potentially confusing language in config precendence
  docs/setup.asciidoc
Labels: agent-nodejs

#2785 chore: update to got@10 and stop there
  .github/dependabot.yml
  .tav.yml
  package-lock.json
  package.json
  test/instrumentation/modules/http/github-423.test.js
Labels: agent-nodejs
