Repository elastic/apm-agent-nodejs, pull requests merged in 2022-05, with the labels that each got.

#2666 feat: 'parent' option to 'agent.captureError()'
  CHANGELOG.asciidoc
  lib/agent.js
  test/agent.test.js
Labels: agent-nodejs

#2669 feat: make TraceParent a local class module
  CHANGELOG.asciidoc
  lib/tracecontext/index.js
  lib/tracecontext/traceparent.js
  package.json
  test/instrumentation/modules/@elastic/elasticsearch.test.js
  test/instrumentation/modules/http/basic.test.js
  test/instrumentation/modules/http/outgoing.test.js
  test/tracecontext/tracecontext.test.js
  test/tracecontext/traceparent.test.js
Labels: agent-nodejs

#2674 fix: possible crash in instrumentation of an incoming HTTP/2 request
  CHANGELOG.asciidoc
  lib/instrumentation/modules/http2.js
  test/instrumentation/modules/http2.test.js
Labels: agent-nodejs

#2667 chore:Publish to npm on release
  .ci/Jenkinsfile
Labels: agent-nodejs

#2676 3.33.0
  CHANGELOG.asciidoc
  CONTRIBUTING.md
  docs/upgrading.asciidoc
  package.json
Labels: agent-nodejs

#2678 test: lock to cassandra:3.11.11 to workaround CASSANDRA-17581 for now
  .ci/docker/docker-compose.yml
  .ci/scripts/test.sh
  test/docker-compose.yml
Labels: agent-nodejs

#2683 test: reduce the number of aws-sdk versions tested
  .tav.yml
Labels: agent-nodejs

#2686 test: fix node version and elasticsearch clients' version compat
  .tav.yml
  package.json
  test/config.test.js
  test/instrumentation/modules/@elastic/elasticsearch.test.js
Labels: agent-nodejs

#2641 feat: OpenTelemetry Bridge
  .eslintrc.json
  .gitignore
  CHANGELOG.asciidoc
  NOTICE.md
  README.md
  docs/api-opentelemetry.asciidoc
  docs/configuration.asciidoc
  docs/index.asciidoc
  docs/opentracing.asciidoc
  examples/opentelemetry-bridge/.gitignore
  examples/opentelemetry-bridge/.npmrc
  examples/opentelemetry-bridge/README.md
  examples/opentelemetry-bridge/otel-sdk.js
  examples/opentelemetry-bridge/package.json
  examples/opentelemetry-bridge/trace-hello-world.js
  examples/opentelemetry-bridge/trace-https-request.js
  lib/agent.js
  lib/config.js
  lib/instrumentation/generic-span.js
  lib/instrumentation/index.js
  lib/instrumentation/run-context/AsyncHooksRunContextManager.js
  lib/instrumentation/run-context/BasicRunContextManager.js
  lib/instrumentation/run-context/RunContext.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  lib/opentelemetry-bridge/OTelBridgeNonRecordingSpan.js
  lib/opentelemetry-bridge/OTelBridgeRunContext.js
  lib/opentelemetry-bridge/OTelContextManager.js
  lib/opentelemetry-bridge/OTelSpan.js
  lib/opentelemetry-bridge/OTelTracer.js
  lib/opentelemetry-bridge/OTelTracerProvider.js
  lib/opentelemetry-bridge/README.md
  lib/opentelemetry-bridge/index.js
  lib/opentelemetry-bridge/oblog.js
  lib/opentelemetry-bridge/opentelemetry-core-mini/README.md
  lib/opentelemetry-bridge/opentelemetry-core-mini/internal/validators.js
  lib/opentelemetry-bridge/opentelemetry-core-mini/trace/TraceState.js
  lib/opentelemetry-bridge/otelutils.js
  lib/opentelemetry-bridge/setup.js
  package.json
  test/opentelemetry-bridge/OTelBridgeNonRecordingSpan.test.js
  test/opentelemetry-bridge/OTelBridgeRunContext.test.js
  test/opentelemetry-bridge/active-span-and-context-interop.test.js
  test/opentelemetry-bridge/fixtures.test.js
  test/opentelemetry-bridge/fixtures/distributed-trace.js
  test/opentelemetry-bridge/fixtures/hit-transaction-max-spans.js
  test/opentelemetry-bridge/fixtures/interface-span.js
  test/opentelemetry-bridge/fixtures/interface-tracer.js
  test/opentelemetry-bridge/fixtures/nonrecordingspan-parent.js
  test/opentelemetry-bridge/fixtures/start-active-span.js
  test/opentelemetry-bridge/fixtures/start-span-with-context.js
  test/opentelemetry-bridge/fixtures/start-span.js
  test/opentelemetry-bridge/fixtures/using-root-context.js
  test/opentelemetry-bridge/interface-ContextManager.test.js
  test/opentelemetry-bridge/otel-bridge-feature.test.js
Labels: agent-nodejs

#2684 feat: use require.main to search for package.json for serviceName/Version
  CHANGELOG.asciidoc
  lib/config.js
  package.json
  test/config.test.js
Labels: agent-nodejs

#2687 feat: setRecorded for traceparent/tracecontext
  lib/tracecontext/index.js
  lib/tracecontext/traceparent.js
  test/tracecontext/traceparent.test.js
Labels: agent-nodejs

#2693 test: fix running benchmarks
  .ci/Jenkinsfile
Labels: agent-nodejs

#2696 test: skip mysql2@2.2.3 in TAV tests to workaround npm v6 install issue with github deps
  .tav.yml
Labels: agent-nodejs

#2692 add traceContinuationStrategy config option; add Span Links API
  CHANGELOG.asciidoc
  docs/agent-api.asciidoc
  docs/configuration.asciidoc
  docs/index.asciidoc
  docs/transaction-api.asciidoc
  index.d.ts
  lib/config.js
  lib/instrumentation/generic-span.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  lib/opentelemetry-bridge/OTelTracer.js
  lib/tracecontext/index.js
  lib/tracecontext/tracestate.js
  test/central-config-enabled.test.js
  test/config.test.js
  test/instrumentation/span.test.js
  test/instrumentation/transaction.test.js
  test/opentelemetry-bridge/fixtures.test.js
  test/traceContinuationStrategy.test.js
  test/tracecontext/tracestate.test.js
  test/types/index.ts
Labels: agent-nodejs

#2697 feat: add "nodejs16.x" lambda runtime to our compatible runtimes
  .ci/Makefile
  CHANGELOG.asciidoc
Labels: agent-nodejs

#2702 synchronize schema spec
  test/integration/api-schema/apm-server-schema/span.json
Labels: automation, agent-nodejs

#2700 chore: update some dev deps to reduce deprecation warnings on install
  package-lock.json
  package.json
Labels: agent-nodejs

#2701 prevent npe when we have no Span as parent
  lib/instrumentation/index.js
  test/agent.test.js
Labels: agent-nodejs, community

#2694 feat: span statistics -- ensure dropped span objects are still created
  lib/instrumentation/index.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  lib/opentelemetry-bridge/OTelTracer.js
  lib/tracecontext/index.js
  test/instrumentation/transaction.test.js
  test/opentelemetry-bridge/fixtures.test.js
  test/opentelemetry-bridge/fixtures/createSpan-returns-null.js
  test/opentelemetry-bridge/fixtures/hit-transaction-max-spans.js
Labels: agent-nodejs

#2705 Feature: Add support for tedious v10 and above
  .tav.yml
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/tedious.js
  package-lock.json
  package.json
  test/config.test.js
  test/instrumentation/modules/tedious.test.js
Labels: agent-nodejs, community

#2706 feat: add span links to AWS SQS ReceiveMessage spans for messages with a traceparent
  CHANGELOG.asciidoc
  examples/trace-sqs-receive-message.js
  examples/trace-sqs-send-message.js
  lib/constants.js
  lib/instrumentation/generic-span.js
  lib/instrumentation/modules/aws-sdk/sqs.js
  lib/opentelemetry-bridge/README.md
  test/instrumentation/modules/aws-sdk/fixtures/sqs.js
  test/instrumentation/modules/aws-sdk/sqs.test.js
Labels: agent-nodejs

#2713 synchronize schema spec
  test/integration/api-schema/apm-server-schema/error.json
  test/integration/api-schema/apm-server-schema/span.json
  test/integration/api-schema/apm-server-schema/transaction.json
Labels: automation, agent-nodejs

#2710 chore: enable dependabot version updates
  .github/dependabot.yml
Labels: agent-nodejs

#2716 fix: get context back for composite spans
  CHANGELOG.asciidoc
  lib/instrumentation/span.js
  test/instrumentation/github-issue-2715.test.js
Labels: agent-nodejs

#2723 3.34.0
  CHANGELOG.asciidoc
  CONTRIBUTING.md
  docs/upgrading.asciidoc
  package-lock.json
  package.json
Labels: agent-nodejs

#2724 fix: build of Lambda layer broke in CI
  .ci/Makefile
Labels: agent-nodejs

#2722 chore: do not add 'community' and 'triage' labels to dependabot PRs
  .github/workflows/labeler.yml
Labels: agent-nodejs

#2714 feat: enable ioredis v5
  .tav.yml
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/ioredis.js
  test/instrumentation/modules/ioredis.test.js
Labels: agent-nodejs, community

#2708 feat: add span links for any 'traceparent' attrs in SQS/SNS-triggered Lambdas
  CHANGELOG.asciidoc
  lib/lambda.js
  test/lambda/fixtures/aws_sns_test_data.json
  test/lambda/fixtures/aws_sqs_test_data.json
  test/lambda/mock/transaction.js
  test/lambda/trace-context.test.js
  test/lambda/transaction.test.js
Labels: agent-nodejs

#2725 Fix Lambda _HANDLER=path/to/file.methodName Form
  CHANGELOG.asciidoc
  lib/lambda.js
  test/lambda/github-issue-2709.test.js
Labels: agent-nodejs

#2736 test: synchronizing json spec
  test/fixtures/json-specs/service_resource_inference.json
Labels: automation, agent-nodejs

#2739 chore: bump to https-pem@3 (devDep) for node-forge@1.3 vuln fixes
  package-lock.json
  package.json
Labels: agent-nodejs

#2738 chore: update devDeps to fastify@3 and @fastify/formbody@6
  package-lock.json
  package.json
  test/sanitize-field-names/fastify.test.js
Labels: agent-nodejs
