Repository elastic/apm-agent-nodejs, pull requests merged in 2022-01, with the labels that each got.

#2506 fix: ensure correct run-context for pg instrumentation
  CHANGELOG.asciidoc
  examples/trace-pg.js
  lib/instrumentation/modules/pg.js
  test/instrumentation/modules/pg/pg.test.js
Labels: agent-nodejs

#2509 fix: ensure correct run context for 'graphql' instrumentation
  CHANGELOG.asciidoc
  examples/trace-graphql.js
  lib/instrumentation/modules/graphql.js
  test/instrumentation/modules/graphql.test.js
Labels: agent-nodejs

#2511 feat: support express-graphql 0.10.0 - 0.12.0
  .tav.yml
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  examples/trace-express-graphql.js
  lib/instrumentation/modules/express-graphql.js
  lib/instrumentation/modules/graphql.js
  package.json
  test/instrumentation/modules/express-graphql.test.js
Labels: agent-nodejs

#2512 fix: ensure correct run context for 'mongodb' instrumentation
  .ci/.jenkins_tav.yml
  .ci/scripts/test.sh
  .tav.yml
  CHANGELOG.asciidoc
  examples/trace-mongodb.js
  lib/instrumentation/modules/mongodb.js
  package.json
  test/instrumentation/modules/mongodb.test.js
Labels: agent-nodejs

#2530 tests: fix test failure due to os.freemem() behaviour change in node v18
  test/metrics/index.test.js
Labels: agent-nodejs

#2528 perf: reduce memory retained by async tasks that outlive their transaction/span
  CHANGELOG.asciidoc
  lib/agent.js
  lib/instrumentation/generic-span.js
  lib/instrumentation/modules/http2.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  test/config.test.js
  test/instrumentation/github-issue-1770.test.js
  test/instrumentation/span.test.js
  test/instrumentation/transaction.test.js
Labels: performance, agent-nodejs

#2532 3.27.0
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  package.json
Labels: agent-nodejs

#2529 docs: refactor troubleshooting docs
  docs/configuration.asciidoc
  docs/troubleshooting.asciidoc
  docs/upgrading.asciidoc
Labels: agent-nodejs

#2535 Neutral naming for apm-agent-nodejs
  .ci/Jenkinsfile
  .ci/jobs/apm-agent-nodejs-mbp.yml
  .ci/jobs/apm-agent-nodejs-schedule-daily.yml
  .ci/jobs/apm-agent-nodejs-schedule-weekly.yml
  .ci/schedule-daily.groovy
  .github/pull_request_template.md
  .github/workflows/lint.yml
  .github/workflows/test.yml
  CHANGELOG.asciidoc
  CONTRIBUTING.md
  DEVELOPMENT.md
  dev-utils/jenkins-build-slow-steps.sh
  docs/configuration.asciidoc
  lib/config.js
  lib/instrumentation/modules/aws-sdk/s3.js
  lib/instrumentation/transaction.js
  lib/lambda.js
  lib/logging.js
  lib/tracecontext/index.js
  test/config.test.js
Labels: automation, agent-nodejs

#2540 tests: fix test failure due to os.freemem() behaviour change in node v17.4.0
  test/metrics/index.test.js
Labels: agent-nodejs

#2538 feat: align on 'unknown-{service.agent.name}-service' default service_name
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  lib/config.js
  test/config.test.js
Labels: agent-nodejs

#2534 docs: correct 'serverTimeout' config var description
  docs/configuration.asciidoc
Labels: agent-nodejs

#2541 docs: update broken links for apm-guide-ref #1385
  CHANGELOG.asciidoc
  docs/agent-api.asciidoc
  docs/configuration.asciidoc
  docs/intro.asciidoc
  docs/log-correlation.asciidoc
  docs/opentracing.asciidoc
  docs/supported-technologies.asciidoc
  docs/troubleshooting.asciidoc
  docs/upgrading.asciidoc
Labels: triage, agent-nodejs, Team:Docs, community

#2542 [3.x] Doc link fixes
  CHANGELOG.asciidoc
  docs/agent-api.asciidoc
  docs/configuration.asciidoc
  docs/intro.asciidoc
  docs/log-correlation.asciidoc
  docs/opentracing.asciidoc
  docs/supported-technologies.asciidoc
Labels: agent-nodejs, Team:Docs

#2544 docs: update log-correlation.asciidoc
  docs/log-correlation.asciidoc
Labels: agent-nodejs, Team:Docs

#2546 feat: Drop unsampled transactions when connected to APM Server 8.0+
  CHANGELOG.asciidoc
  lib/config.js
  lib/instrumentation/index.js
  lib/noop-transport.js
  package.json
  test/_capturing_transport.js
  test/_mock_apm_server.js
  test/_mock_http_client.js
  test/_mock_http_client_states.js
  test/agent.test.js
  test/central-config-enabled.test.js
  test/config.test.js
  test/fixtures/do-not-trace-self.js
  test/instrumentation/index.test.js
  test/integration/allow-invalid-cert.test.js
  test/integration/api-schema/basic.test.js
  test/integration/api-schema/capture-error-log-stack-traces.test.js
  test/integration/api-schema/capture-span-stack-traces.test.js
  test/integration/api-schema/source-lines-error-frames.test.js
  test/integration/api-schema/source-lines-span-frames.test.js
  test/integration/no-sampling.test.js
  test/integration/server-url-path.test.js
  test/integration/skip-internal-http-spans.test.js
  test/integration/socket-close.test.js
  test/integration/verify-server-ca-cert.test.js
  test/outcome.test.js
  test/transaction-sampling.test.js
Labels: agent-nodejs

#2548 fix: ensure correct run context for 'mongodb-core' instrumentation
  CHANGELOG.asciidoc
  lib/instrumentation/modules/mongodb-core.js
  test/instrumentation/modules/mongodb-core.test.js
Labels: agent-nodejs

#2549 fix: ensure correct run context for 'cassandra-driver' instrumentation
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  examples/trace-cassandra-driver.js
  lib/instrumentation/modules/cassandra-driver.js
  test/instrumentation/modules/cassandra-driver/index.test.js
Labels: agent-nodejs

#2550 fix: ensure correct run context for '@elastic/elasticsearch' instrumentation
  .ci/.jenkins_tav.yml
  .ci/scripts/test.sh
  .tav.yml
  CHANGELOG.asciidoc
  examples/trace-elasticsearch7.js
  examples/trace-elasticsearch8.js
  lib/instrumentation/elasticsearch-shared.js
  lib/instrumentation/modules/@elastic/elasticsearch.js
  lib/instrumentation/modules/elasticsearch.js
  package.json
  test/instrumentation/modules/@elastic/elasticsearch.test.js
  test/instrumentation/modules/elasticsearch.test.js
Labels: agent-nodejs

#2551 fix: ensure correct run context for 'elasticsearch' (legacy) instrumentation
  CHANGELOG.asciidoc
  lib/instrumentation/modules/elasticsearch.js
  test/instrumentation/modules/elasticsearch.test.js
Labels: agent-nodejs

#2444 fix: drop no-longer-necessary half-disabling of instrumentations
  CHANGELOG.asciidoc
  lib/instrumentation/modules/mysql.js
  lib/instrumentation/modules/redis.js
Labels: agent-nodejs

#2552 feat: introduce "exit spans" and mark S3 spans as exit spans
  .tav.yml
  CHANGELOG.asciidoc
  docs/agent-api.asciidoc
  docs/transaction-api.asciidoc
  index.d.ts
  lib/agent.js
  lib/instrumentation/http-shared.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/aws-sdk/s3.js
  lib/instrumentation/span.js
  lib/instrumentation/transaction.js
  test/instrumentation/modules/aws-sdk/s3.test.js
  test/types/index.ts
Labels: agent-nodejs
