Repository elastic/apm-agent-nodejs, pull requests merged in 2023-05, with the labels that each got.

#3301 Make mysql2 3.x.x function
  .tav.yml
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/mysql2.js
  package-lock.json
  package.json
  test/config.test.js
  test/instrumentation/modules/mysql2/mysql.test.js
  test/instrumentation/modules/mysql2/pool-release-1.test.js
Labels: agent-nodejs, community

#2681 feat(fastify): add captureBody support
  .tav.yml
  CHANGELOG.asciidoc
  lib/instrumentation/modules/fastify.js
  test/instrumentation/modules/fastify/fastify.test.js
  test/sanitize-field-names/fastify.test.js
Labels: agent-nodejs, community, 8.9-candidate

#3287 feat: add instrumentation for aws-sdk S3 client
  .ci/tav.json
  .tav.yml
  CHANGELOG.asciidoc
  dev-utils/aws-sdk-s3-client-tav-versions.sh
  docs/supported-technologies.asciidoc
  lib/instrumentation/index.js
  lib/instrumentation/modules/@aws-sdk/client-s3.js
  lib/instrumentation/modules/@aws-sdk/smithy-client.js
  package-lock.json
  package.json
  test/instrumentation/modules/@aws-sdk/client-s3.test.js
  test/instrumentation/modules/@aws-sdk/fixtures/use-client-s3.js
Labels: agent-nodejs

#3312 test: fix @aws-sdk/client-s3 TAV test failures
  .ci/scripts/test.sh
  .tav.yml
  dev-utils/aws-sdk-s3-client-tav-versions.sh
  docs/supported-technologies.asciidoc
  test/instrumentation/modules/@aws-sdk/client-s3.test.js
  test/instrumentation/modules/aws-sdk/s3.test.js
Labels: agent-nodejs

#3314 test: fix fastify TAV test failures
  .tav.yml
Labels: agent-nodejs

#3305 fix: support Lambda instrumentation for `contextManager: 'patch'`; refactor Lambda tests
  docs/lambda.asciidoc
  lib/lambda.js
  test/lambda/callbacks.test.js
  test/lambda/context.test.js
  test/lambda/fixtures/aws_s3_batch_test_data.json
  test/lambda/fixtures/context.json
  test/lambda/github-issue-2709.test.js
  test/lambda/lambda.test.js
  test/lambda/metadata.test.js
  test/lambda/metadata2.test.js
  test/lambda/mock/agent.js
  test/lambda/mock/transaction.js
  test/lambda/promises.test.js
  test/lambda/trace-context.test.js
  test/lambda/trans-setDefaultName.test.js
  test/lambda/transaction.test.js
  test/lambda/transaction2.test.js
  test/lambda/wrap-bundled-handler.test.js
  test/lambda/wrapper.test.js
Labels: agent-nodejs

#3307 test: restore testing of Azure Functions on node >=18.x
  test/instrumentation/azure-functions/azure-functions.test.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package-lock.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package.json
Labels: agent-nodejs

#3308 chore: fix bitrot.js dev util for recent changes
  dev-utils/bitrot.js
Labels: agent-nodejs

#3304 tests: stop testing 'express-graphql' instrumentation
  .ci/tav.json
  .npmrc
  .tav.yml
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  docs/supported-technologies.asciidoc
  docs/upgrade-to-v3.asciidoc
  examples/trace-apollo-server-express.js
  examples/trace-express-graphql.js
  lib/instrumentation/modules/graphql.js
  package-lock.json
  package.json
  test/config.test.js
  test/instrumentation/modules/express-graphql.test.js
Labels: agent-nodejs

#3309 chore: update nvm
  .ci/docker/node-edge-container/Dockerfile
  .ci/scripts/prepare-benchmarks-env.sh
Labels: agent-nodejs

#3203 feat: Add Apollo 4 support
  .ci/tav.json
  .tav.yml
  docs/supported-technologies.asciidoc
  lib/instrumentation/index.js
  lib/instrumentation/modules/@apollo/server.js
  package-lock.json
  package.json
  test/config.test.js
  test/instrumentation/modules/@apollo/server.test.js
Labels: agent-nodejs, community, 8.9-candidate

#3317 test: fix running fastify.test.js with node v8
  test/instrumentation/modules/fastify/fastify.test.js
Labels: agent-nodejs

#3315 test: drop node 14 from RC tests now that it is EOL
  .github/workflows/edge.yml
Labels: agent-nodejs

#3293 chore, test: test driver improvements
  DEVELOPMENT.md
  TESTING.md
  package-lock.json
  package.json
  test/central-config-disabled.test.js
  test/central-config-enabled.test.js
  test/script/docker/run_docs.sh
  test/script/run_tests.sh
  test/start/env/test.test.js
  test/start/file/test.test.js
  test/test.js
Labels: agent-nodejs

#3318 chore: sync package-lock so 'npm ci' can work
  package-lock.json
Labels: agent-nodejs

#3321 test: reduce TAV test matrix for slowest jobs
  .ci/tav.json
  .tav.yml
  dev-utils/tav-versions-fastify.sh
  package-lock.json
  package.json
  test/instrumentation/modules/bluebird/bluebird.test.js
Labels: agent-nodejs

#3319 chore: fix dev-utils/ci-tav-slow-jobs.sh
  dev-utils/ci-tav-slow-jobs.sh
Labels: agent-nodejs

#3325 fix: correct supported versions of knex to exclude 0.9.0
  .tav.yml
  docs/supported-technologies.asciidoc
Labels: agent-nodejs

#3322 Send cookies explicitly into `context.request`'s transaction
  CHANGELOG.asciidoc
  lib/agent.js
  lib/filters/http-headers.js
  lib/parsers.js
  package-lock.json
  package.json
  test/filters.test.js
  test/instrumentation/transaction.test.js
Labels: agent-nodejs

#3335 test: workaround SQS test failures with aws-sdk >=2.1372.0 but not testing latest aws-sdk versions for now
  .tav.yml
Labels: agent-nodejs

#3246 action: support github commands for the tav modules
  .ci/generate-github-tav-matrix.sh
  .github/workflows/tav-command.yml
  .github/workflows/tav.yml
Labels: agent-nodejs

#3333 chore: mark filterHttpHeaders config option as deprecated
  CHANGELOG.asciidoc
  CONTRIBUTING.md
  docs/configuration.asciidoc
  lib/config.js
  lib/parsers.js
  test/config.test.js
Labels: agent-nodejs

#3340 chore: add 'npm run lint:tav'
  .tav.yml
  dev-utils/lint-tav-json.js
  package.json
Labels: agent-nodejs

#3339 Various small updates
  .ci/docker/node-container/Dockerfile
  .nvmrc
  TESTING.md
Labels: agent-nodejs

#3336 3.46.0
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  package-lock.json
  package.json
Labels: agent-nodejs

#3341 chore, test: bump @elastic/elasticsearch-canary dep, drop its TAV testing, bump ES server version
  .ci/docker/docker-compose.yml
  .ci/tav.json
  .github/workflows/test.yml
  .tav.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: agent-nodejs

#3358 chore: move config.js to its own module
  lib/agent.js
  lib/config/config.js
  lib/config/normalizers.js
  lib/config/schema.js
  lib/instrumentation/generic-span.js
  lib/instrumentation/index.js
  lib/instrumentation/transaction.js
  test/agent.test.js
  test/central-config-enabled.test.js
  test/config.test.js
  test/config/normalizers.test.js
  test/instrumentation/modules/@elastic/elasticsearch.test.js
  test/instrumentation/modules/http/ignore-url-does-not-leak-trans.test.js
  test/traceContinuationStrategy.test.js
Labels: agent-nodejs

#3359 chore: ignore mimic-response updates since they are not instrumented
  .github/dependabot.yml
Labels: agent-nodejs

#3337 feat: add `apm.setGlobalLabel()`
  CHANGELOG.asciidoc
  docs/agent-api.asciidoc
  index.d.ts
  lib/agent.js
  test/agent.test.js
Labels: agent-nodejs, community

#3366 chore: add tedious v16 in tav tests and agent checks
  .tav.yml
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  lib/instrumentation/modules/tedious.js
  package-lock.json
  package.json
  test/config.test.js
  test/instrumentation/modules/tedious.test.js
Labels: agent-nodejs

#3370 docs: Fixes broken es logs link in `main`
  docs/log-correlation.asciidoc
Labels: agent-nodejs, Team:Docs

#3371 docs: Fixes broken es logs link in `3.x`
  docs/log-correlation.asciidoc
Labels: agent-nodejs, Team:Docs

#3380 docs: fix broken links to APM docs
  docs/agent-api.asciidoc
  docs/log-correlation.asciidoc
  docs/opentracing.asciidoc
Labels: agent-nodejs

#3392 test, refactor: simplify pg.test.js
  test/instrumentation/modules/pg/pg.test.js
Labels: agent-nodejs
