Repository elastic/apm-agent-nodejs, pull requests merged in 2023-01, with the labels that each got.

#3078 synchronize schema spec
  test/integration/api-schema/apm-server-schema/metadata.json
Labels: automation, agent-nodejs

#3082 synchronize schema spec
  test/integration/api-schema/apm-server-schema/span.json
  test/integration/api-schema/apm-server-schema/transaction.json
Labels: automation, agent-nodejs

#3086 fix bitrot.js dev-util to work for Next.js versions
  dev-utils/bitrot.js
Labels: agent-nodejs

#3100 fix TAV test failure with @elastic/elasticsearch@8.6.0 and node v14
  lib/errors.js
  package-lock.json
  package.json
  test/errors.test.js
Labels: agent-nodejs

#3071 feat: Azure Functions
  .eslintrc.json
  CHANGELOG.asciidoc
  NOTICE.md
  docs/azure-functions.asciidoc
  docs/images/azure-functions-configuration.png
  docs/set-up.asciidoc
  docs/supported-technologies.asciidoc
  examples/an-azure-function-app/.gitignore
  examples/an-azure-function-app/.npmrc
  examples/an-azure-function-app/Bye/function.json
  examples/an-azure-function-app/Bye/index.js
  examples/an-azure-function-app/Hi/function.json
  examples/an-azure-function-app/Hi/index.js
  examples/an-azure-function-app/README.md
  examples/an-azure-function-app/host.json
  examples/an-azure-function-app/initapm.js
  examples/an-azure-function-app/local.settings.json
  examples/an-azure-function-app/package.json
  lib/config.js
  lib/instrumentation/azure-functions.js
  lib/instrumentation/index.js
  lib/ritm.js
  package-lock.json
  package.json
  test/_utils.js
  test/instrumentation/azure-functions/azure-functions.test.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/.gitignore
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFn1/function.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFn1/index.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnBindingsRes/function.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnBindingsRes/index.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnContextDone/function.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnContextDone/index.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnDistTraceA/function.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnDistTraceA/index.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnDistTraceB/function.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnDistTraceB/index.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnError/function.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnError/index.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnReturnContext/function.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnReturnContext/index.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnReturnObject/function.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnReturnObject/index.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnReturnResponseData/function.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnReturnResponseData/index.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnReturnString/function.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnReturnString/index.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnRouteTemplate/function.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/HttpFnRouteTemplate/index.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/README.md
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/host.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/initapm.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/local.settings.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package-lock.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package.json
  test/instrumentation/modules/next/next.test.js
Labels: agent-nodejs

#3090 fix: instrumentation of `http.request` et al has a few edge cases
  CHANGELOG.asciidoc
  lib/instrumentation/http-shared.js
  test/instrumentation/modules/http/outgoing.test.js
  test/traceContinuationStrategy.test.js
Labels: agent-nodejs

#2805 ci: send github actions and tests as distributed traces
  .github/workflows/opentelemetry.yml
  .github/workflows/test.yml
  test/script/run_tests.sh
Labels: automation, agent-nodejs, Team:Automation

#3041 feat: service.agent.activation_method metadata field
  CHANGELOG.asciidoc
  lib/activation-method.js
  lib/agent.js
  lib/config.js
  package-lock.json
  package.json
  test/activation-method/activation-method.test.js
  test/activation-method/fixtures/.npmrc
  test/activation-method/fixtures/hi.js
  test/activation-method/fixtures/import1.mjs
  test/activation-method/fixtures/import2.mjs
  test/activation-method/fixtures/package.json
  test/activation-method/fixtures/require1.js
  test/activation-method/fixtures/require2.js
  test/agent.test.js
Labels: agent-nodejs

#3101 chore: switch to transaction.type="scheduled" for timer-triggered Azure Functions
  lib/instrumentation/azure-functions.js
Labels: agent-nodejs

#3105 fix: ensure `transaction.dropped_spans_stats[*].duration.sum.us` is an int
  CHANGELOG.asciidoc
  lib/instrumentation/dropped-span-stats.js
  test/instrumentation/dropped-span-stats.test.js
Labels: agent-nodejs

#3106 test: fix TAV=@hapi/hapi test failure with node v8
  .tav.yml
  test/_is_hapi_incompat.js
  test/instrumentation/modules/hapi/set-framework-hapihapi.test.js
  test/instrumentation/modules/hapi/shared.js
Labels: agent-nodejs

#3103 3.42.0
  CHANGELOG.asciidoc
  package-lock.json
  package.json
Labels: agent-nodejs

#3112 test: run 'npm ci' on a second test run if the first 'npm ci' possibly failed
  test/instrumentation/modules/next/next.test.js
Labels: agent-nodejs

#3122 chore: correct comment on ES client instrumentation
  lib/instrumentation/modules/@elastic/elasticsearch.js
Labels: agent-nodejs

#3120 fix: activation_method='k8s-attach' now uses explicit ELASTIC_APM_ACTIVATION_METHOD
  CHANGELOG.asciidoc
  lib/activation-method.js
  test/activation-method/activation-method.test.js
Labels: agent-nodejs

#3123 test: skip Azure Functions tests on Windows
  package.json
  test/instrumentation/azure-functions/azure-functions.test.js
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package-lock.json
  test/instrumentation/azure-functions/fixtures/AJsAzureFnApp/package.json
Labels: agent-nodejs

#3125 action: snapshoty
  .ci/Jenkinsfile
  .github/workflows/opentelemetry.yml
  .github/workflows/snapshoty.yml
Labels: automation, agent-nodejs, Team:Automation

#3129 snapshoty: migrate to github actions
  .ci/snapshoty.yml
Labels: automation, agent-nodejs, Team:Automation

#3121 fix: add opentelemetryBridgeEnabled option to TS declaration for AgentConfigOptions
  index.d.ts
Labels: agent-nodejs, community

#3130 fix: add missing 'contextManager' config var to TypeScript types
  CHANGELOG.asciidoc
  index.d.ts
Labels: agent-nodejs

#3128 action: lint and ELASTIC_APM_CONTEXT_MANAGER=patch
  .ci/.jenkins_nodejs.yml
  .ci/Jenkinsfile
  .ci/packer_cache.sh
  .ci/scripts/test_basic.sh
  .ci/scripts/test_types_babel_esm.sh
  .github/workflows/test.yml
Labels: automation, agent-nodejs, Team:Automation

#3126 action: edge
  .ci/.jenkins_nightly_nodejs.yml
  .ci/.jenkins_rc_nodejs.yml
  .ci/Jenkinsfile
  .github/workflows/edge.yml
  .github/workflows/opentelemetry.yml
Labels: automation, agent-nodejs, Team:Automation

#3132 test: reduce the number of aws-sdk versions tested in TAV tests
  .tav.yml
Labels: agent-nodejs
