Repository elastic/apm-agent-nodejs, pull requests merged in 2023-02, with the labels that each got.

#3133 chore: refactor parsers to avoid usage of parseurl package
  lib/instrumentation/express-utils.js
  package.json
  test/instrumentation/express-utils.test.js
Labels: agent-nodejs, community

#3131 feat: support for Lambda function URL and ELB-triggered Lambdas
  CHANGELOG.asciidoc
  lib/lambda.js
  lib/parsers.js
  test/lambda/fixtures/aws_elb_test_data.json
  test/lambda/mock/transaction.js
  test/lambda/trace-context.test.js
  test/lambda/transaction2.test.js
Labels: agent-nodejs

#3139 update package-lock from recent change removing azure-functions-core-tools top-level dep
  package-lock.json
Labels: agent-nodejs

#3153 Add update-spec updatecli workflow
  .ci/update-specs.yml
  .github/workflows/opentelemetry.yml
  .github/workflows/update-specs.yml
  test/integration/api-schema/apm-server-schema/log.json
Labels: triage, agent-nodejs, community

#3160 Fix sha source in updatecli update-specs.yml
  .ci/update-specs.yml
Labels: triage, agent-nodejs, community

#3162 Use composite action for updatecli workflow
  .github/workflows/update-specs.yml
Labels: triage, agent-nodejs, community

#3167 feat: Make Agent.flush() return a Promise if no callback is passed as param
  CHANGELOG.asciidoc
  docs/agent-api.asciidoc
  index.d.ts
  lib/agent.js
  test/agent.test.js
Labels: agent-nodejs, community

#3175 docs: minor fix in README for Azure Functions example
  examples/an-azure-function-app/README.md
Labels: agent-nodejs

#3177 mongodb@5 support
  .tav.yml
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  examples/trace-mongodb.js
  lib/instrumentation/modules/mongodb.js
  package-lock.json
  package.json
  test/_is_mongodb_incompat.js
  test/config.test.js
  test/instrumentation/modules/mongodb.test.js
Labels: agent-nodejs
