Repository elastic/apm-agent-nodejs, pull requests merged in 2023-06, with the labels that each got.

#3383 chore: add logging preamble
  lib/agent.js
  lib/config/config.js
  lib/config/normalizers.js
  lib/config/schema.js
  test/_mock_logger.js
  test/config.test.js
  test/config/normalizers.test.js
  test/logging-preamble.test.js
Labels: agent-nodejs

#3406 ci: fix status checks
  .github/workflows/edge.yml
  .github/workflows/lint.yml
  .github/workflows/opentelemetry.yml
  .github/workflows/snapshoty.yml
  .github/workflows/test-docs.yml
  .github/workflows/test.yml
Labels: triage, agent-nodejs, community

#3401 small changes
  .ci/scripts/docker-test.sh
  examples/trace-http.js
  lib/agent.js
Labels: agent-nodejs

#3410 fix: do not start the Agent in "start.js" when in a Worker thread
  CHANGELOG.asciidoc
  docs/set-up.asciidoc
  lib/config/config.js
  package.json
  start-next.js
  start.js
Labels: agent-nodejs

#3412 chore: drop our redact-secrets fork
  lib/redact-secrets/index.js
  lib/redact-secrets/is-secret.js
  package-lock.json
  package.json
  test/redact-secrets/is-secret.test.js
  test/redact-secrets/redact-secrets.test.js
Labels: agent-nodejs

#3431 test: fix a flaky test that was relying on www.google.com:81 behaviour
  test/http-request.test.js
Labels: agent-nodejs

#3427 fix: avoid redaction of response headers
  CHANGELOG.asciidoc
  lib/filters/sanitize-field-names.js
  lib/parsers.js
  test/parsers.test.js
  test/sanitize-field-names/main.test.js
Labels: agent-nodejs

#3429 3.47.0
  CHANGELOG.asciidoc
  docs/agent-api.asciidoc
  docs/set-up.asciidoc
  package-lock.json
  package.json
Labels: agent-nodejs

#3409 Chore (upgrade eslint config and packages)
  .eslintrc.json
  dev-utils/bitrot.js
  examples/.eslintrc.json
  examples/trace-graphql.js
  examples/trace-handlebars.js
  examples/trace-pg.js
  examples/trace-pug.js
  examples/trace-tedious.js
  examples/trace-ws.js
  lib/instrumentation/modules/elasticsearch.js
  lib/instrumentation/modules/graphql.js
  lib/instrumentation/modules/mysql.js
  lib/instrumentation/span-compression.js
  lib/tracecontext/tracestate.js
  package-lock.json
  package.json
  test/_utils.js
  test/instrumentation/modules/http/aborted-requests-enabled.test.js
  test/instrumentation/modules/http2.test.js
  test/metrics/index.test.js
  test/script/run_tests.sh
Labels: agent-nodejs, community

#3433 test: do not run 'lint' as part of 'npm run test'
  test/script/run_tests.sh
Labels: agent-nodejs

#3334 test: convert sqs.test.js over to use localstack for end-to-end tests (similar to s3.test.js)
  .ci/docker/docker-compose.yml
  .github/workflows/test.yml
  .tav.yml
  dev-utils/aws-sdk-tav-versions.sh
  docs/supported-technologies.asciidoc
  examples/trace-sqs-send-message.js
  package-lock.json
  package.json
  test/docker-compose.yml
  test/instrumentation/modules/@aws-sdk/client-s3.test.js
  test/instrumentation/modules/aws-sdk/fixtures/sqs.js
  test/instrumentation/modules/aws-sdk/fixtures/use-s3.js
  test/instrumentation/modules/aws-sdk/fixtures/use-sqs.js
  test/instrumentation/modules/aws-sdk/s3.test.js
  test/instrumentation/modules/aws-sdk/sqs.test.js
Labels: agent-nodejs

#3381 feat: initial ESM support
  .eslintrc.json
  .tav.yml
  CHANGELOG.asciidoc
  TESTING.md
  docs/esm.asciidoc
  docs/index.asciidoc
  docs/supported-technologies.asciidoc
  lib/instrumentation/http-shared.js
  lib/instrumentation/index.js
  lib/instrumentation/modules/fastify.js
  lib/instrumentation/modules/http.js
  lib/instrumentation/modules/https.js
  loader.mjs
  package-lock.json
  package.json
  test/_agent.js
  test/_utils.js
  test/config.test.js
  test/esm/index.mjs
  test/instrumentation/modules/@aws-sdk/client-s3.test.js
  test/instrumentation/modules/@aws-sdk/fixtures/use-client-s3.mjs
  test/instrumentation/modules/express/express-fixtures.test.js
  test/instrumentation/modules/fastify/fastify.test.js
  test/instrumentation/modules/fixtures/static/style.css
  test/instrumentation/modules/fixtures/use-express.mjs
  test/instrumentation/modules/fixtures/use-fastify-errorCodes.js
  test/instrumentation/modules/fixtures/use-fastify.js
  test/instrumentation/modules/fixtures/use-fastify.mjs
  test/instrumentation/modules/fixtures/use-ioredis.mjs
  test/instrumentation/modules/fixtures/use-knex-pg.mjs
  test/instrumentation/modules/fixtures/use-pg.mjs
  test/instrumentation/modules/http/fixtures/load-http-twice.mjs
  test/instrumentation/modules/http/fixtures/load-http.js
  test/instrumentation/modules/http/fixtures/load-http.mjs
  test/instrumentation/modules/http/fixtures/use-dynamic-import.mjs
  test/instrumentation/modules/http/fixtures/use-http-get.mjs
  test/instrumentation/modules/http/fixtures/use-http-server.mjs
  test/instrumentation/modules/http/fixtures/use-https-get.mjs
  test/instrumentation/modules/http/http-esm.test.js
  test/instrumentation/modules/ioredis.test.js
  test/instrumentation/modules/pg/knex.test.js
  test/instrumentation/modules/pg/pg.test.js
  test/script/run_tests.sh
  test/testconsts.js
Labels: agent-nodejs

#3443 fix: 🐛setGlobalLabel should not error when apm is inactive
  CHANGELOG.asciidoc
  lib/agent.js
  test/agent.test.js
Labels: agent-nodejs, community

#3451 fix: set the transaction parent for an incoming HTTP/2 request
  CHANGELOG.asciidoc
  lib/instrumentation/modules/http2.js
Labels: triage, agent-nodejs, community
