Repository elastic/apm-agent-nodejs, pull requests merged in 2024-01, with the labels that each got.

#3813 Add link to APM attacher docs
  docs/set-up.asciidoc
Labels: agent-nodejs

#3812 chore: adapt `update-tav-versions.js` to the new TAV@5 syntax
  .tav.yml
  dev-utils/tav-versions-fastify.sh
  dev-utils/update-tav-versions.js
Labels: agent-nodejs

#3815 fix: NODE_ENV envvar for 'environment' was broken in v4.2.0
  CHANGELOG.asciidoc
  lib/apm-client/http-apm-client/README.md
  lib/apm-client/http-apm-client/index.js
  lib/config/schema.js
  test/apm-client/http-apm-client/lib/utils.js
  test/config/config.test.js
Labels: agent-nodejs

#3763 [Automation] Update JSON specs
  test/fixtures/json-specs/container_metadata_discovery.json
Labels: automation, agent-nodejs

#3819 chore: support 'K8S_ATTACH' value for 'ELASTIC_APM_ACTIVATION_METHOD'
  CHANGELOG.asciidoc
  lib/activation-method.js
Labels: agent-nodejs

#3824 test: lock Node.js v18 testing to v18.18.2 as a workaround for IITM double-import issue
  .ci/tav.json
  .github/workflows/tav-command.yml
  .github/workflows/tav.yml
  .github/workflows/test.yml
  CHANGELOG.asciidoc
  dev-utils/lint-tav-json.js
Labels: agent-nodejs

#3821 chore: support 'K8S_ATTACH' value for 'ELASTIC_APM_ACTIVATION_METHOD'
  CHANGELOG.asciidoc
  lib/activation-method.js
Labels: agent-nodejs

#3822 release 4.4.0
  CHANGELOG.asciidoc
  package-lock.json
  package.json
Labels: agent-nodejs

#3837 chore: clarify koa-router instrumentation range
  lib/instrumentation/modules/koa-router.js
  lib/instrumentation/modules/mongodb.js
Labels: agent-nodejs

#3845 chore: updatecli with dynamic specs
  .ci/updatecli.d/update-json-specs.yml
  .ci/updatecli.d/update-specs.yml
  .ci/updatecli/updatecli.d/update-json-specs.yml
  .ci/updatecli/updatecli.d/update-specs.yml
  .ci/updatecli/values.yml
  .github/workflows/updatecli.yml
Labels: agent-nodejs

#3853 github-action: use wildcards for discovering all the workflows
  .github/workflows/opentelemetry.yml
Labels: ci, agent-nodejs
