Repository elastic/apm-agent-nodejs, pull requests merged in 2024-07, with the labels that each got.

#4122 [Automation] Update JSON server schema specs
  test/integration/api-schema/apm-server-schema/metadata.json
Labels: dependencies

#4098 fix: add missing methods to noop-transaction
  lib/instrumentation/noop-transaction.js
Labels: triage, community

#4119 fix: allow file config to override true default values
  lib/config/schema.js
  test/start/file/elastic-apm-node.js
  test/start/file/test.test.js
Labels: community
